// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.5
// Generated from: nitro_printing.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

// --- Enums ---
typedef enum {
  PRINTSTATE_IDLE = 0,
  PRINTSTATE_PRINTING = 1,
  PRINTSTATE_COMPLETED = 2,
  PRINTSTATE_CANCELLED = 3,
  PRINTSTATE_FAILED = 4,
  PRINTSTATE_PAUSED = 5,
} PrintState;

typedef enum {
  PRINTQUALITY_DRAFT = 0,
  PRINTQUALITY_NORMAL = 1,
  PRINTQUALITY_HIGH = 2,
  PRINTQUALITY_BEST = 3,
} PrintQuality;

typedef enum {
  PAPERSIZE_A4 = 0,
  PAPERSIZE_A5 = 1,
  PAPERSIZE_LETTER = 2,
  PAPERSIZE_LEGAL = 3,
  PAPERSIZE_CUSTOM = 4,
} PaperSize;

typedef enum {
  DOCUMENTTYPE_PLAIN_TEXT = 0,
  DOCUMENTTYPE_HTML = 1,
  DOCUMENTTYPE_PDF = 2,
  DOCUMENTTYPE_IMAGE = 3,
} DocumentType;

typedef enum {
  MEDIATYPE_PLAIN = 0,
  MEDIATYPE_GLOSSY = 1,
  MEDIATYPE_MATTE = 2,
  MEDIATYPE_PHOTO = 3,
  MEDIATYPE_LABEL = 4,
  MEDIATYPE_ENVELOPE = 5,
} MediaType;

typedef enum {
  PRINTDIALOGSTATE_IDLE = 0,
  PRINTDIALOGSTATE_SHOWING = 1,
  PRINTDIALOGSTATE_CONFIRMED = 2,
  PRINTDIALOGSTATE_CANCELLED = 3,
} PrintDialogState;

// --- Structs ---
#ifndef NITRO_STRUCT_PREVIEWRESULT_DEFINED
#define NITRO_STRUCT_PREVIEWRESULT_DEFINED
typedef struct {
  uint8_t* bytes; /* zero-copy */
  int64_t length; 
} PreviewResult;
#endif // NITRO_STRUCT_PREVIEWRESULT_DEFINED

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_printing_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_printing_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_printing_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_printing_get_error(void);
NITRO_EXPORT void nitro_printing_clear_error(void);



// Methods
NITRO_EXPORT int8_t nitro_printing_is_printing_supported(NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_printing_get_printers_count(NitroError* _nitro_err);
NITRO_EXPORT const char* nitro_printing_get_printer_driver_version(const char* printerId, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_printing_get_all_printers();
NITRO_EXPORT uint8_t* nitro_printing_get_printer_at(int64_t index);
NITRO_EXPORT uint8_t* nitro_printing_get_default_printer();
NITRO_EXPORT uint8_t* nitro_printing_get_printer_capabilities(const char* printerId);
NITRO_EXPORT void* nitro_printing_print_text(const char* text, void* settings);
NITRO_EXPORT void* nitro_printing_print_image(uint8_t* imageData, int64_t imageData_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_pdf(uint8_t* pdfData, int64_t pdfData_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_document(void* document, void* settings);
NITRO_EXPORT int8_t nitro_printing_print_file(const char* filePath, void* settings);
NITRO_EXPORT void* nitro_printing_print_batch(void* documents, int8_t stopOnError, void* settings);
NITRO_EXPORT void* nitro_printing_show_print_dialog(void* document, void* initialSettings);
NITRO_EXPORT void* nitro_printing_render_preview(void* document, void* settings);
NITRO_EXPORT int64_t nitro_printing_get_page_count(void* document);
NITRO_EXPORT int8_t nitro_printing_print_to_file(void* document, const char* outputPath, void* settings);
NITRO_EXPORT int8_t nitro_printing_cancel_print_job(const char* jobId);
NITRO_EXPORT int8_t nitro_printing_pause_print_job(const char* jobId);
NITRO_EXPORT int8_t nitro_printing_resume_print_job(const char* jobId);
NITRO_EXPORT int8_t nitro_printing_clear_print_queue();
NITRO_EXPORT int64_t nitro_printing_get_print_jobs_count();
NITRO_EXPORT uint8_t* nitro_printing_get_print_job_at(int64_t index);
NITRO_EXPORT uint8_t* nitro_printing_get_print_job_status(const char* jobId);
NITRO_EXPORT int8_t nitro_printing_start_printer_discovery();
NITRO_EXPORT int8_t nitro_printing_stop_printer_discovery();
NITRO_EXPORT int8_t nitro_printing_test_printer_connection(const char* printerId, void* timeoutSeconds);
NITRO_EXPORT int8_t nitro_printing_set_default_printer(const char* printerId);
NITRO_EXPORT int8_t nitro_printing_open_system_print_queue(const char* printerId);
NITRO_EXPORT int8_t nitro_printing_open_printer_properties(const char* printerId);
NITRO_EXPORT void* nitro_printing_print_raw(uint8_t* data, int64_t data_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_esc_pos(uint8_t* escPosData, int64_t escPosData_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_zpl(const char* zpl, void* settings);
NITRO_EXPORT int8_t nitro_printing_cancel_raw_print();
NITRO_EXPORT uint8_t* nitro_printing_get_printer_status_detail(const char* printerId, void* timeoutSeconds);

// Streams
// Stream<PrintJobUpdate> onPrintJobChanged
NITRO_EXPORT void nitro_printing_register_on_print_job_changed_stream(int64_t dart_port);
NITRO_EXPORT void nitro_printing_release_on_print_job_changed_stream(int64_t dart_port);
// Stream<PrinterStatus> onPrinterStatusChanged
NITRO_EXPORT void nitro_printing_register_on_printer_status_changed_stream(int64_t dart_port);
NITRO_EXPORT void nitro_printing_release_on_printer_status_changed_stream(int64_t dart_port);
// Stream<DiscoveredPrinter> onPrinterDiscovered
NITRO_EXPORT void nitro_printing_register_on_printer_discovered_stream(int64_t dart_port);
NITRO_EXPORT void nitro_printing_release_on_printer_discovered_stream(int64_t dart_port);

// Struct release functions
NITRO_EXPORT void nitro_printing_release_PreviewResult(void* ptr);

#ifdef __cplusplus
}
#endif
