// Generated by Nitrogen Modules. Do not edit.
// Generator version: 0.3.5
// Generated from: nitro_printing.native.dart
import Foundation
import Combine

// --- Enums ---
public enum PrintState: Int64 {
  case idle = 0
  case printing = 1
  case completed = 2
  case cancelled = 3
  case failed = 4
  case paused = 5
}

public enum PrintQuality: Int64 {
  case draft = 0
  case normal = 1
  case high = 2
  case best = 3
}

public enum PaperSize: Int64 {
  case a4 = 0
  case a5 = 1
  case letter = 2
  case legal = 3
  case custom = 4
}

public enum DocumentType: Int64 {
  case plainText = 0
  case html = 1
  case pdf = 2
  case image = 3
}

public enum MediaType: Int64 {
  case plain = 0
  case glossy = 1
  case matte = 2
  case photo = 3
  case label = 4
  case envelope = 5
}

// --- Structs ---
public struct PrinterInfo {
  public var id: String
  public var name: String
  public var address: String
  public var isDefault: Bool
  public var isAvailable: Bool
}

// C-ABI shadow — layout matches the C typedef PrinterInfo
fileprivate struct _PrinterInfoC {
  var id: UnsafeMutablePointer<CChar>?
  var name: UnsafeMutablePointer<CChar>?
  var address: UnsafeMutablePointer<CChar>?
  var isDefault: Int8
  var isAvailable: Int8

  static func fromSwift(_ s: PrinterInfo) -> _PrinterInfoC {
    return _PrinterInfoC(
      id: strdup(s.id),
      name: strdup(s.name),
      address: strdup(s.address),
      isDefault: s.isDefault ? 1 : 0,
      isAvailable: s.isAvailable ? 1 : 0
    )
  }

  func toSwift() -> PrinterInfo {
    return PrinterInfo(
      id: id.map { String(cString: $0) } ?? "",
      name: name.map { String(cString: $0) } ?? "",
      address: address.map { String(cString: $0) } ?? "",
      isDefault: isDefault != 0,
      isAvailable: isAvailable != 0
    )
  }
}

public struct PrinterCapabilities {
  public var supportsColor: Bool
  public var supportsDuplex: Bool
  public var supportsCopy: Bool
  public var maxCopies: Int64
  public var minMarginTop: Double
  public var minMarginBottom: Double
  public var minMarginLeft: Double
  public var minMarginRight: Double
  public var supportsA4: Bool
  public var supportsA5: Bool
  public var supportsLetter: Bool
  public var supportsLegal: Bool
  public var supportsDraftQuality: Bool
  public var supportsNormalQuality: Bool
  public var supportsHighQuality: Bool
  public var supportsBestQuality: Bool
  public var maxResolutionDpi: Int64
  public var supportsCustomPaper: Bool
  public var supportsBorderless: Bool
  public var inputTrays: String
}

// C-ABI shadow — layout matches the C typedef PrinterCapabilities
fileprivate struct _PrinterCapabilitiesC {
  var supportsColor: Int8
  var supportsDuplex: Int8
  var supportsCopy: Int8
  var maxCopies: Int64
  var minMarginTop: Double
  var minMarginBottom: Double
  var minMarginLeft: Double
  var minMarginRight: Double
  var supportsA4: Int8
  var supportsA5: Int8
  var supportsLetter: Int8
  var supportsLegal: Int8
  var supportsDraftQuality: Int8
  var supportsNormalQuality: Int8
  var supportsHighQuality: Int8
  var supportsBestQuality: Int8
  var maxResolutionDpi: Int64
  var supportsCustomPaper: Int8
  var supportsBorderless: Int8
  var inputTrays: UnsafeMutablePointer<CChar>?

  static func fromSwift(_ s: PrinterCapabilities) -> _PrinterCapabilitiesC {
    return _PrinterCapabilitiesC(
      supportsColor: s.supportsColor ? 1 : 0,
      supportsDuplex: s.supportsDuplex ? 1 : 0,
      supportsCopy: s.supportsCopy ? 1 : 0,
      maxCopies: s.maxCopies,
      minMarginTop: s.minMarginTop,
      minMarginBottom: s.minMarginBottom,
      minMarginLeft: s.minMarginLeft,
      minMarginRight: s.minMarginRight,
      supportsA4: s.supportsA4 ? 1 : 0,
      supportsA5: s.supportsA5 ? 1 : 0,
      supportsLetter: s.supportsLetter ? 1 : 0,
      supportsLegal: s.supportsLegal ? 1 : 0,
      supportsDraftQuality: s.supportsDraftQuality ? 1 : 0,
      supportsNormalQuality: s.supportsNormalQuality ? 1 : 0,
      supportsHighQuality: s.supportsHighQuality ? 1 : 0,
      supportsBestQuality: s.supportsBestQuality ? 1 : 0,
      maxResolutionDpi: s.maxResolutionDpi,
      supportsCustomPaper: s.supportsCustomPaper ? 1 : 0,
      supportsBorderless: s.supportsBorderless ? 1 : 0,
      inputTrays: strdup(s.inputTrays)
    )
  }

  func toSwift() -> PrinterCapabilities {
    return PrinterCapabilities(
      supportsColor: supportsColor != 0,
      supportsDuplex: supportsDuplex != 0,
      supportsCopy: supportsCopy != 0,
      maxCopies: maxCopies,
      minMarginTop: minMarginTop,
      minMarginBottom: minMarginBottom,
      minMarginLeft: minMarginLeft,
      minMarginRight: minMarginRight,
      supportsA4: supportsA4 != 0,
      supportsA5: supportsA5 != 0,
      supportsLetter: supportsLetter != 0,
      supportsLegal: supportsLegal != 0,
      supportsDraftQuality: supportsDraftQuality != 0,
      supportsNormalQuality: supportsNormalQuality != 0,
      supportsHighQuality: supportsHighQuality != 0,
      supportsBestQuality: supportsBestQuality != 0,
      maxResolutionDpi: maxResolutionDpi,
      supportsCustomPaper: supportsCustomPaper != 0,
      supportsBorderless: supportsBorderless != 0,
      inputTrays: inputTrays.map { String(cString: $0) } ?? ""
    )
  }
}

public struct PrintSettings {
  public var printerId: String
  public var paperSize: PaperSize
  public var orientationDegrees: Double
  public var quality: PrintQuality
  public var copies: Int64
  public var collate: Bool
  public var duplex: Bool
  public var color: Bool
  public var marginTop: Double
  public var marginBottom: Double
  public var marginLeft: Double
  public var marginRight: Double
  public var jobName: String
  public var pagesPerSheet: Int64
  public var showPrintDialog: Bool
  public var pageRangeFrom: Int64
  public var pageRangeTo: Int64
  public var customPaperWidth: Double
  public var customPaperHeight: Double
  public var fitToPage: Bool
  public var mediaType: MediaType
  public var headerText: String
  public var footerText: String
  public var inputTray: String
  public var networkTimeoutSeconds: Int64
}

// C-ABI shadow — layout matches the C typedef PrintSettings
fileprivate struct _PrintSettingsC {
  var printerId: UnsafeMutablePointer<CChar>?
  var paperSize: Int32
  var orientationDegrees: Double
  var quality: Int32
  var copies: Int64
  var collate: Int8
  var duplex: Int8
  var color: Int8
  var marginTop: Double
  var marginBottom: Double
  var marginLeft: Double
  var marginRight: Double
  var jobName: UnsafeMutablePointer<CChar>?
  var pagesPerSheet: Int64
  var showPrintDialog: Int8
  var pageRangeFrom: Int64
  var pageRangeTo: Int64
  var customPaperWidth: Double
  var customPaperHeight: Double
  var fitToPage: Int8
  var mediaType: Int32
  var headerText: UnsafeMutablePointer<CChar>?
  var footerText: UnsafeMutablePointer<CChar>?
  var inputTray: UnsafeMutablePointer<CChar>?
  var networkTimeoutSeconds: Int64

  static func fromSwift(_ s: PrintSettings) -> _PrintSettingsC {
    return _PrintSettingsC(
      printerId: strdup(s.printerId),
      paperSize: Int32(s.paperSize.rawValue),
      orientationDegrees: s.orientationDegrees,
      quality: Int32(s.quality.rawValue),
      copies: s.copies,
      collate: s.collate ? 1 : 0,
      duplex: s.duplex ? 1 : 0,
      color: s.color ? 1 : 0,
      marginTop: s.marginTop,
      marginBottom: s.marginBottom,
      marginLeft: s.marginLeft,
      marginRight: s.marginRight,
      jobName: strdup(s.jobName),
      pagesPerSheet: s.pagesPerSheet,
      showPrintDialog: s.showPrintDialog ? 1 : 0,
      pageRangeFrom: s.pageRangeFrom,
      pageRangeTo: s.pageRangeTo,
      customPaperWidth: s.customPaperWidth,
      customPaperHeight: s.customPaperHeight,
      fitToPage: s.fitToPage ? 1 : 0,
      mediaType: Int32(s.mediaType.rawValue),
      headerText: strdup(s.headerText),
      footerText: strdup(s.footerText),
      inputTray: strdup(s.inputTray),
      networkTimeoutSeconds: s.networkTimeoutSeconds
    )
  }

  func toSwift() -> PrintSettings {
    return PrintSettings(
      printerId: printerId.map { String(cString: $0) } ?? "",
      paperSize: PaperSize(rawValue: Int64(paperSize))!,
      orientationDegrees: orientationDegrees,
      quality: PrintQuality(rawValue: Int64(quality))!,
      copies: copies,
      collate: collate != 0,
      duplex: duplex != 0,
      color: color != 0,
      marginTop: marginTop,
      marginBottom: marginBottom,
      marginLeft: marginLeft,
      marginRight: marginRight,
      jobName: jobName.map { String(cString: $0) } ?? "",
      pagesPerSheet: pagesPerSheet,
      showPrintDialog: showPrintDialog != 0,
      pageRangeFrom: pageRangeFrom,
      pageRangeTo: pageRangeTo,
      customPaperWidth: customPaperWidth,
      customPaperHeight: customPaperHeight,
      fitToPage: fitToPage != 0,
      mediaType: MediaType(rawValue: Int64(mediaType))!,
      headerText: headerText.map { String(cString: $0) } ?? "",
      footerText: footerText.map { String(cString: $0) } ?? "",
      inputTray: inputTray.map { String(cString: $0) } ?? "",
      networkTimeoutSeconds: networkTimeoutSeconds
    )
  }
}

public struct PrintDocument {
  public var id: String
  public var title: String
  public var type: DocumentType
  public var data: Data
}

// C-ABI shadow — layout matches the C typedef PrintDocument
fileprivate struct _PrintDocumentC {
  var id: UnsafeMutablePointer<CChar>?
  var title: UnsafeMutablePointer<CChar>?
  var type: Int32
  var data: UnsafeMutablePointer<UInt8>?
  var dataLength: Int64

  static func fromSwift(_ s: PrintDocument) -> _PrintDocumentC {
    var _buf_data: UnsafeMutablePointer<UInt8>? = nil
    var _len_data: Int64 = 0
    if !s.data.isEmpty {
      _buf_data = UnsafeMutablePointer<UInt8>.allocate(capacity: s.data.count)
      s.data.copyBytes(to: _buf_data!, count: s.data.count)
      _len_data = Int64(s.data.count)
    }
    return _PrintDocumentC(
      id: strdup(s.id),
      title: strdup(s.title),
      type: Int32(s.type.rawValue),
      data: _buf_data,
      dataLength: _len_data
    )
  }

  func toSwift() -> PrintDocument {
    let _arr_data = data.map { Data(bytes: $0, count: Int(dataLength)) } ?? Data()
    return PrintDocument(
      id: id.map { String(cString: $0) } ?? "",
      title: title.map { String(cString: $0) } ?? "",
      type: DocumentType(rawValue: Int64(type))!,
      data: _arr_data
    )
  }
}

public struct PrintJob {
  public var id: String
  public var printerId: String
  public var documentTitle: String
  public var state: PrintState
  public var progress: Int64
  public var createdAtMillis: Int64
  public var completedAtMillis: Int64
  public var errorMessage: String
  public var pagesPrinted: Int64
}

// C-ABI shadow — layout matches the C typedef PrintJob
fileprivate struct _PrintJobC {
  var id: UnsafeMutablePointer<CChar>?
  var printerId: UnsafeMutablePointer<CChar>?
  var documentTitle: UnsafeMutablePointer<CChar>?
  var state: Int32
  var progress: Int64
  var createdAtMillis: Int64
  var completedAtMillis: Int64
  var errorMessage: UnsafeMutablePointer<CChar>?
  var pagesPrinted: Int64

  static func fromSwift(_ s: PrintJob) -> _PrintJobC {
    return _PrintJobC(
      id: strdup(s.id),
      printerId: strdup(s.printerId),
      documentTitle: strdup(s.documentTitle),
      state: Int32(s.state.rawValue),
      progress: s.progress,
      createdAtMillis: s.createdAtMillis,
      completedAtMillis: s.completedAtMillis,
      errorMessage: strdup(s.errorMessage),
      pagesPrinted: s.pagesPrinted
    )
  }

  func toSwift() -> PrintJob {
    return PrintJob(
      id: id.map { String(cString: $0) } ?? "",
      printerId: printerId.map { String(cString: $0) } ?? "",
      documentTitle: documentTitle.map { String(cString: $0) } ?? "",
      state: PrintState(rawValue: Int64(state))!,
      progress: progress,
      createdAtMillis: createdAtMillis,
      completedAtMillis: completedAtMillis,
      errorMessage: errorMessage.map { String(cString: $0) } ?? "",
      pagesPrinted: pagesPrinted
    )
  }
}

public struct PrintResult {
  public var success: Bool
  public var jobId: String
  public var errorMessage: String
  public var errorCode: String
}

// C-ABI shadow — layout matches the C typedef PrintResult
fileprivate struct _PrintResultC {
  var success: Int8
  var jobId: UnsafeMutablePointer<CChar>?
  var errorMessage: UnsafeMutablePointer<CChar>?
  var errorCode: UnsafeMutablePointer<CChar>?

  static func fromSwift(_ s: PrintResult) -> _PrintResultC {
    return _PrintResultC(
      success: s.success ? 1 : 0,
      jobId: strdup(s.jobId),
      errorMessage: strdup(s.errorMessage),
      errorCode: strdup(s.errorCode)
    )
  }

  func toSwift() -> PrintResult {
    return PrintResult(
      success: success != 0,
      jobId: jobId.map { String(cString: $0) } ?? "",
      errorMessage: errorMessage.map { String(cString: $0) } ?? "",
      errorCode: errorCode.map { String(cString: $0) } ?? ""
    )
  }
}

public struct PrintJobUpdate {
  public var jobId: String
  public var state: PrintState
  public var progress: Int64
  public var message: String
}

// C-ABI shadow — layout matches the C typedef PrintJobUpdate
fileprivate struct _PrintJobUpdateC {
  var jobId: UnsafeMutablePointer<CChar>?
  var state: Int32
  var progress: Int64
  var message: UnsafeMutablePointer<CChar>?

  static func fromSwift(_ s: PrintJobUpdate) -> _PrintJobUpdateC {
    return _PrintJobUpdateC(
      jobId: strdup(s.jobId),
      state: Int32(s.state.rawValue),
      progress: s.progress,
      message: strdup(s.message)
    )
  }

  func toSwift() -> PrintJobUpdate {
    return PrintJobUpdate(
      jobId: jobId.map { String(cString: $0) } ?? "",
      state: PrintState(rawValue: Int64(state))!,
      progress: progress,
      message: message.map { String(cString: $0) } ?? ""
    )
  }
}

public struct PrinterStatus {
  public var printerId: String
  public var isOnline: Bool
  public var isPrinting: Bool
  public var jobsInQueue: Int64
  public var statusMessage: String
  public var inkLevel: Int64
  public var tonerLevel: Int64
  public var paperLevel: Int64
  public var errorCode: String
  public var isWarmingUp: Bool
}

// C-ABI shadow — layout matches the C typedef PrinterStatus
fileprivate struct _PrinterStatusC {
  var printerId: UnsafeMutablePointer<CChar>?
  var isOnline: Int8
  var isPrinting: Int8
  var jobsInQueue: Int64
  var statusMessage: UnsafeMutablePointer<CChar>?
  var inkLevel: Int64
  var tonerLevel: Int64
  var paperLevel: Int64
  var errorCode: UnsafeMutablePointer<CChar>?
  var isWarmingUp: Int8

  static func fromSwift(_ s: PrinterStatus) -> _PrinterStatusC {
    return _PrinterStatusC(
      printerId: strdup(s.printerId),
      isOnline: s.isOnline ? 1 : 0,
      isPrinting: s.isPrinting ? 1 : 0,
      jobsInQueue: s.jobsInQueue,
      statusMessage: strdup(s.statusMessage),
      inkLevel: s.inkLevel,
      tonerLevel: s.tonerLevel,
      paperLevel: s.paperLevel,
      errorCode: strdup(s.errorCode),
      isWarmingUp: s.isWarmingUp ? 1 : 0
    )
  }

  func toSwift() -> PrinterStatus {
    return PrinterStatus(
      printerId: printerId.map { String(cString: $0) } ?? "",
      isOnline: isOnline != 0,
      isPrinting: isPrinting != 0,
      jobsInQueue: jobsInQueue,
      statusMessage: statusMessage.map { String(cString: $0) } ?? "",
      inkLevel: inkLevel,
      tonerLevel: tonerLevel,
      paperLevel: paperLevel,
      errorCode: errorCode.map { String(cString: $0) } ?? "",
      isWarmingUp: isWarmingUp != 0
    )
  }
}

public struct PreviewResult {
  public var bytes: UnsafeMutablePointer<UInt8>?
  public var length: Int64
}

// C-ABI shadow — layout matches the C typedef PreviewResult
fileprivate struct _PreviewResultC {
  var bytes: UnsafeMutablePointer<UInt8>?
  var length: Int64

  static func fromSwift(_ s: PreviewResult) -> _PreviewResultC {
    return _PreviewResultC(
      bytes: s.bytes,
      length: s.length
    )
  }

  func toSwift() -> PreviewResult {
    return PreviewResult(
      bytes: bytes,
      length: length
    )
  }
}

public struct DiscoveredPrinter {
  public var id: String
  public var name: String
  public var host: String
  public var port: Int64
  public var serviceType: String
  public var uri: String
  public var isAvailable: Bool
}

// C-ABI shadow — layout matches the C typedef DiscoveredPrinter
fileprivate struct _DiscoveredPrinterC {
  var id: UnsafeMutablePointer<CChar>?
  var name: UnsafeMutablePointer<CChar>?
  var host: UnsafeMutablePointer<CChar>?
  var port: Int64
  var serviceType: UnsafeMutablePointer<CChar>?
  var uri: UnsafeMutablePointer<CChar>?
  var isAvailable: Int8

  static func fromSwift(_ s: DiscoveredPrinter) -> _DiscoveredPrinterC {
    return _DiscoveredPrinterC(
      id: strdup(s.id),
      name: strdup(s.name),
      host: strdup(s.host),
      port: s.port,
      serviceType: strdup(s.serviceType),
      uri: strdup(s.uri),
      isAvailable: s.isAvailable ? 1 : 0
    )
  }

  func toSwift() -> DiscoveredPrinter {
    return DiscoveredPrinter(
      id: id.map { String(cString: $0) } ?? "",
      name: name.map { String(cString: $0) } ?? "",
      host: host.map { String(cString: $0) } ?? "",
      port: port,
      serviceType: serviceType.map { String(cString: $0) } ?? "",
      uri: uri.map { String(cString: $0) } ?? "",
      isAvailable: isAvailable != 0
    )
  }
}

public struct PrinterStatusDetail {
  public var printerId: String
  public var isOnline: Bool
  public var isReady: Bool
  public var hasPaperJam: Bool
  public var isOutOfPaper: Bool
  public var isOutOfInk: Bool
  public var inkLevelBlack: Int64
  public var inkLevelCyan: Int64
  public var inkLevelMagenta: Int64
  public var inkLevelYellow: Int64
  public var tonerLevel: Int64
  public var paperLevel: Int64
  public var jobsInQueue: Int64
  public var isWarmingUp: Bool
  public var printerState: String
  public var stateReasons: String
  public var statusMessage: String
  public var errorCode: String
  public var isDuplexSupported: Bool
  public var isColorSupported: Bool
}

// C-ABI shadow — layout matches the C typedef PrinterStatusDetail
fileprivate struct _PrinterStatusDetailC {
  var printerId: UnsafeMutablePointer<CChar>?
  var isOnline: Int8
  var isReady: Int8
  var hasPaperJam: Int8
  var isOutOfPaper: Int8
  var isOutOfInk: Int8
  var inkLevelBlack: Int64
  var inkLevelCyan: Int64
  var inkLevelMagenta: Int64
  var inkLevelYellow: Int64
  var tonerLevel: Int64
  var paperLevel: Int64
  var jobsInQueue: Int64
  var isWarmingUp: Int8
  var printerState: UnsafeMutablePointer<CChar>?
  var stateReasons: UnsafeMutablePointer<CChar>?
  var statusMessage: UnsafeMutablePointer<CChar>?
  var errorCode: UnsafeMutablePointer<CChar>?
  var isDuplexSupported: Int8
  var isColorSupported: Int8

  static func fromSwift(_ s: PrinterStatusDetail) -> _PrinterStatusDetailC {
    return _PrinterStatusDetailC(
      printerId: strdup(s.printerId),
      isOnline: s.isOnline ? 1 : 0,
      isReady: s.isReady ? 1 : 0,
      hasPaperJam: s.hasPaperJam ? 1 : 0,
      isOutOfPaper: s.isOutOfPaper ? 1 : 0,
      isOutOfInk: s.isOutOfInk ? 1 : 0,
      inkLevelBlack: s.inkLevelBlack,
      inkLevelCyan: s.inkLevelCyan,
      inkLevelMagenta: s.inkLevelMagenta,
      inkLevelYellow: s.inkLevelYellow,
      tonerLevel: s.tonerLevel,
      paperLevel: s.paperLevel,
      jobsInQueue: s.jobsInQueue,
      isWarmingUp: s.isWarmingUp ? 1 : 0,
      printerState: strdup(s.printerState),
      stateReasons: strdup(s.stateReasons),
      statusMessage: strdup(s.statusMessage),
      errorCode: strdup(s.errorCode),
      isDuplexSupported: s.isDuplexSupported ? 1 : 0,
      isColorSupported: s.isColorSupported ? 1 : 0
    )
  }

  func toSwift() -> PrinterStatusDetail {
    return PrinterStatusDetail(
      printerId: printerId.map { String(cString: $0) } ?? "",
      isOnline: isOnline != 0,
      isReady: isReady != 0,
      hasPaperJam: hasPaperJam != 0,
      isOutOfPaper: isOutOfPaper != 0,
      isOutOfInk: isOutOfInk != 0,
      inkLevelBlack: inkLevelBlack,
      inkLevelCyan: inkLevelCyan,
      inkLevelMagenta: inkLevelMagenta,
      inkLevelYellow: inkLevelYellow,
      tonerLevel: tonerLevel,
      paperLevel: paperLevel,
      jobsInQueue: jobsInQueue,
      isWarmingUp: isWarmingUp != 0,
      printerState: printerState.map { String(cString: $0) } ?? "",
      stateReasons: stateReasons.map { String(cString: $0) } ?? "",
      statusMessage: statusMessage.map { String(cString: $0) } ?? "",
      errorCode: errorCode.map { String(cString: $0) } ?? "",
      isDuplexSupported: isDuplexSupported != 0,
      isColorSupported: isColorSupported != 0
    )
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension PrinterInfo {
  public static func fromReader(_ r: NitroRecordReader) -> PrinterInfo {
    return PrinterInfo(
      id: r.readString(),
      name: r.readString(),
      address: r.readString(),
      isDefault: r.readBool(),
      isAvailable: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(id)
    writer.writeString(name)
    writer.writeString(address)
    writer.writeBool(isDefault)
    writer.writeBool(isAvailable)
  }
}

public class NitroRecordWriter {
    public var bytes: [UInt8] = []
    public init() {}
    public func writeInt(_ v: Int64) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeInt32(_ v: Int32) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeDouble(_ v: Double) {
        var val = v.bitPattern.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeBool(_ v: Bool) {
        bytes.append(v ? 1 : 0)
    }
    public func writeString(_ v: String) {
        let utf8 = Array(v.utf8)
        writeInt32(Int32(utf8.count))
        bytes.append(contentsOf: utf8)
    }
    public func writeNullTag(_ isNull: Bool) {
        bytes.append(isNull ? 0 : 1)
    }
    public func writeBlob(_ v: Data) {
        writeInt32(Int32(v.count))
        bytes.append(contentsOf: Array(v))
    }
    public func toNative() -> UnsafeMutablePointer<UInt8>? {
        let total = 4 + bytes.count
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
        var length = Int32(bytes.count).littleEndian
        withUnsafeBytes(of: &length) {
            ptr.update(from: $0.baseAddress!.assumingMemoryBound(to: UInt8.self), count: 4)
        }
        ptr.advanced(by: 4).update(from: bytes, count: bytes.count)
        return ptr
    }
    public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        let w = NitroRecordWriter()
        w.writeInt32(Int32(items.count))
        for item in items { writeItem(w, item) }
        return w.toNative()
    }
}

public class NitroRecordReader {
    public let bytes: UnsafeMutablePointer<UInt8>
    public var pos: Int = 0
    public init(ptr: UnsafeMutablePointer<UInt8>) {
        self.bytes = ptr.advanced(by: 4)
    }
    public init(payload: UnsafeMutablePointer<UInt8>) {
        self.bytes = payload
    }
    public func readInt() -> Int64 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int64.self)
        pos += 8
        return Int64(littleEndian: v)
    }
    public func readInt32() -> Int32 {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: Int32.self)
        pos += 4
        return Int32(littleEndian: v)
    }
    public func readDouble() -> Double {
        let v = UnsafeRawPointer(bytes.advanced(by: pos)).load(as: UInt64.self)
        pos += 8
        return Double(bitPattern: UInt64(littleEndian: v))
    }
    public func readBool() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v != 0
    }
    public func readString() -> String {
        let len = Int(readInt32())
        let s = String(bytesNoCopy: UnsafeMutableRawPointer(bytes.advanced(by: pos)), length: len, encoding: .utf8, freeWhenDone: false) ?? ""
        pos += len
        return s
    }
    public func readNullTag() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v == 0
    }
    public func readBlob() -> Data {
        let len = Int(readInt32())
        let data = Data(bytes: bytes.advanced(by: pos), count: len)
        pos += len
        return data
    }
    public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
        let len = Int(readInt32())
        if (len == 0) { return nil }
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
        ptr.initialize(from: bytes.advanced(by: pos), count: len)
        pos += len
        return ptr
    }
    public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
}

/**
 * Protocol for the NitroPrinting module.
 * Conform to this in your Swift source code.
 */
public protocol HybridNitroPrintingProtocol: AnyObject {
    // source: nitro_printing.native.dart:20
    func isPrintingSupported() -> Bool
    // source: nitro_printing.native.dart:21
    func getPrintersCount() -> Int64
    // source: nitro_printing.native.dart:24
    func getAllPrinters() -> [PrinterInfo]
    // source: nitro_printing.native.dart:25
    func getPrinterAt(index: Int64) -> PrinterInfo
    // source: nitro_printing.native.dart:26
    func getDefaultPrinter() -> PrinterInfo
    // source: nitro_printing.native.dart:27
    func getPrinterDriverVersion(printerId: String) -> String
    // source: nitro_printing.native.dart:28
    func getPrinterCapabilities(printerId: String) -> PrinterCapabilities
    // source: nitro_printing.native.dart:33
    func printText(text: String, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:36
    func printImage(imageData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:42
    func printPdf(pdfData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:45
    func printDocument(document: PrintDocument, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:51
    func printFile(filePath: String, settings: PrintSettings?) async throws -> Bool
    // source: nitro_printing.native.dart:57
    func renderPreview(document: PrintDocument, settings: PrintSettings?) async throws -> PreviewResult
    // source: nitro_printing.native.dart:64
    func getPageCount(document: PrintDocument) async throws -> Int64
    // source: nitro_printing.native.dart:68
    func printToFile(document: PrintDocument, outputPath: String, settings: PrintSettings?) async throws -> Bool
    // source: nitro_printing.native.dart:77
    func cancelPrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:80
    func pausePrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:83
    func resumePrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:86
    func clearPrintQueue() async throws -> Bool
    // source: nitro_printing.native.dart:89
    func getPrintJobsCount() async throws -> Int64
    // source: nitro_printing.native.dart:92
    func getPrintJobAt(index: Int64) async throws -> PrintJob
    // source: nitro_printing.native.dart:96
    func getPrintJobStatus(jobId: String) async throws -> PrintJob
    // source: nitro_printing.native.dart:103
    func startPrinterDiscovery() async throws -> Bool
    // source: nitro_printing.native.dart:106
    func stopPrinterDiscovery() async throws -> Bool
    // source: nitro_printing.native.dart:112
    func testPrinterConnection(printerId: String, timeoutSeconds: Int64?) async throws -> Bool
    // source: nitro_printing.native.dart:116
    func setDefaultPrinter(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:126
    func openSystemPrintQueue(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:130
    func openPrinterProperties(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:138
    func printRaw(data: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:143
    func printEscPos(escPosData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:151
    func printZpl(zpl: String, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:157
    func cancelRawPrint() async throws -> Bool
    // source: nitro_printing.native.dart:164
    func getPrinterStatusDetail(printerId: String, timeoutSeconds: Int64?) async throws -> PrinterStatusDetail
    var onPrintJobChanged: AnyPublisher<PrintJobUpdate, Never> { get }
    var onPrinterStatusChanged: AnyPublisher<PrinterStatus, Never> { get }
    var onPrinterDiscovered: AnyPublisher<DiscoveredPrinter, Never> { get }
}

public class NitroPrintingRegistry {
    public static var impl: HybridNitroPrintingProtocol?

    public static func register(_ impl: HybridNitroPrintingProtocol) {
        NitroPrintingRegistry.impl = impl
    }

    // Stream: onPrintJobChanged cancellables keyed by dartPort
    public static var _onPrintJobChangedCancellables = [Int64: AnyCancellable]()

    // Stream: onPrinterStatusChanged cancellables keyed by dartPort
    public static var _onPrinterStatusChangedCancellables = [Int64: AnyCancellable]()

    // Stream: onPrinterDiscovered cancellables keyed by dartPort
    public static var _onPrinterDiscoveredCancellables = [Int64: AnyCancellable]()
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_printing.native.dart:20
@_cdecl("_nitro_printing_call_isPrintingSupported")
public func _nitro_printing_call_isPrintingSupported() -> Int8 {
    return Int8((NitroPrintingRegistry.impl?.isPrintingSupported() ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:21
@_cdecl("_nitro_printing_call_getPrintersCount")
public func _nitro_printing_call_getPrintersCount() -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    return impl.getPrintersCount()
}

// source: nitro_printing.native.dart:24
@_cdecl("_nitro_printing_call_getAllPrinters")
public func _nitro_printing_call_getAllPrinters() -> UnsafeMutablePointer<UInt8>? {
    guard let r = NitroPrintingRegistry.impl?.getAllPrinters() else { return nil }
    return NitroRecordWriter.encodeList(r) { w, e in e.writeFields(w) }
}

// source: nitro_printing.native.dart:25
@_cdecl("_nitro_printing_call_getPrinterAt")
public func _nitro_printing_call_getPrinterAt(_ index: Int64) -> UnsafeMutableRawPointer? {
    guard let result = NitroPrintingRegistry.impl?.getPrinterAt(index: index) else { return nil }
    let ptr = UnsafeMutablePointer<_PrinterInfoC>.allocate(capacity: 1)
    ptr.initialize(to: _PrinterInfoC.fromSwift(result))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:26
@_cdecl("_nitro_printing_call_getDefaultPrinter")
public func _nitro_printing_call_getDefaultPrinter() -> UnsafeMutableRawPointer? {
    guard let result = NitroPrintingRegistry.impl?.getDefaultPrinter() else { return nil }
    let ptr = UnsafeMutablePointer<_PrinterInfoC>.allocate(capacity: 1)
    ptr.initialize(to: _PrinterInfoC.fromSwift(result))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:27
@_cdecl("_nitro_printing_call_getPrinterDriverVersion")
public func _nitro_printing_call_getPrinterDriverVersion(_ printerId: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    return strdup(NitroPrintingRegistry.impl?.getPrinterDriverVersion(printerId: printerIdStr) ?? "")
}

// source: nitro_printing.native.dart:28
@_cdecl("_nitro_printing_call_getPrinterCapabilities")
public func _nitro_printing_call_getPrinterCapabilities(_ printerId: UnsafePointer<CChar>?) -> UnsafeMutableRawPointer? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let result = NitroPrintingRegistry.impl?.getPrinterCapabilities(printerId: printerIdStr) else { return nil }
    let ptr = UnsafeMutablePointer<_PrinterCapabilitiesC>.allocate(capacity: 1)
    ptr.initialize(to: _PrinterCapabilitiesC.fromSwift(result))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:33
@_cdecl("_nitro_printing_call_printText")
public func _nitro_printing_call_printText(_ text: UnsafePointer<CChar>?, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let textStr = text != nil ? String(cString: text!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printText(text: textStr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:36
@_cdecl("_nitro_printing_call_printImage")
public func _nitro_printing_call_printImage(_ imageData: UnsafeMutablePointer<UInt8>?, _ imageData_length: Int64, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let imageDataArr = imageData.map { Data(UnsafeBufferPointer(start: $0, count: Int(imageData_length))) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printImage(imageData: imageDataArr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:42
@_cdecl("_nitro_printing_call_printPdf")
public func _nitro_printing_call_printPdf(_ pdfData: UnsafeMutablePointer<UInt8>?, _ pdfData_length: Int64, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let pdfDataArr = pdfData.map { Data(UnsafeBufferPointer(start: $0, count: Int(pdfData_length))) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printPdf(pdfData: pdfDataArr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:45
@_cdecl("_nitro_printing_call_printDocument")
public func _nitro_printing_call_printDocument(_ document: UnsafeRawPointer?, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printDocument(document: document!.assumingMemoryBound(to: _PrintDocumentC.self).pointee.toSwift(), settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:51
@_cdecl("_nitro_printing_call_printFile")
public func _nitro_printing_call_printFile(_ filePath: UnsafePointer<CChar>?, _ settings: UnsafeRawPointer?) -> Int8 {
    let filePathStr = filePath != nil ? String(cString: filePath!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.printFile(filePath: filePathStr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:57
@_cdecl("_nitro_printing_call_renderPreview")
public func _nitro_printing_call_renderPreview(_ document: UnsafeRawPointer?, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PreviewResult? = nil
    Task.detached {
        result = try? await impl.renderPreview(document: document!.assumingMemoryBound(to: _PrintDocumentC.self).pointee.toSwift(), settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PreviewResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PreviewResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:64
@_cdecl("_nitro_printing_call_getPageCount")
public func _nitro_printing_call_getPageCount(_ document: UnsafeRawPointer?) -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.getPageCount(document: document!.assumingMemoryBound(to: _PrintDocumentC.self).pointee.toSwift())
        sema.signal()
    }
    sema.wait()
    return result ?? 0
}

// source: nitro_printing.native.dart:68
@_cdecl("_nitro_printing_call_printToFile")
public func _nitro_printing_call_printToFile(_ document: UnsafeRawPointer?, _ outputPath: UnsafePointer<CChar>?, _ settings: UnsafeRawPointer?) -> Int8 {
    let outputPathStr = outputPath != nil ? String(cString: outputPath!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.printToFile(document: document!.assumingMemoryBound(to: _PrintDocumentC.self).pointee.toSwift(), outputPath: outputPathStr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:77
@_cdecl("_nitro_printing_call_cancelPrintJob")
public func _nitro_printing_call_cancelPrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.cancelPrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:80
@_cdecl("_nitro_printing_call_pausePrintJob")
public func _nitro_printing_call_pausePrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.pausePrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:83
@_cdecl("_nitro_printing_call_resumePrintJob")
public func _nitro_printing_call_resumePrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.resumePrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:86
@_cdecl("_nitro_printing_call_clearPrintQueue")
public func _nitro_printing_call_clearPrintQueue() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.clearPrintQueue()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:89
@_cdecl("_nitro_printing_call_getPrintJobsCount")
public func _nitro_printing_call_getPrintJobsCount() -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.getPrintJobsCount()
        sema.signal()
    }
    sema.wait()
    return result ?? 0
}

// source: nitro_printing.native.dart:92
@_cdecl("_nitro_printing_call_getPrintJobAt")
public func _nitro_printing_call_getPrintJobAt(_ index: Int64) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintJob? = nil
    Task.detached {
        result = try? await impl.getPrintJobAt(index: index)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintJobC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintJobC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:96
@_cdecl("_nitro_printing_call_getPrintJobStatus")
public func _nitro_printing_call_getPrintJobStatus(_ jobId: UnsafePointer<CChar>?) -> UnsafeMutableRawPointer? {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintJob? = nil
    Task.detached {
        result = try? await impl.getPrintJobStatus(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintJobC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintJobC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:103
@_cdecl("_nitro_printing_call_startPrinterDiscovery")
public func _nitro_printing_call_startPrinterDiscovery() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.startPrinterDiscovery()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:106
@_cdecl("_nitro_printing_call_stopPrinterDiscovery")
public func _nitro_printing_call_stopPrinterDiscovery() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.stopPrinterDiscovery()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:112
@_cdecl("_nitro_printing_call_testPrinterConnection")
public func _nitro_printing_call_testPrinterConnection(_ printerId: UnsafePointer<CChar>?, _ timeoutSeconds: Int64) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.testPrinterConnection(printerId: printerIdStr, timeoutSeconds: timeoutSeconds)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:116
@_cdecl("_nitro_printing_call_setDefaultPrinter")
public func _nitro_printing_call_setDefaultPrinter(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.setDefaultPrinter(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:126
@_cdecl("_nitro_printing_call_openSystemPrintQueue")
public func _nitro_printing_call_openSystemPrintQueue(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.openSystemPrintQueue(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:130
@_cdecl("_nitro_printing_call_openPrinterProperties")
public func _nitro_printing_call_openPrinterProperties(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.openPrinterProperties(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:138
@_cdecl("_nitro_printing_call_printRaw")
public func _nitro_printing_call_printRaw(_ data: UnsafeMutablePointer<UInt8>?, _ data_length: Int64, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let dataArr = data.map { Data(UnsafeBufferPointer(start: $0, count: Int(data_length))) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printRaw(data: dataArr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:143
@_cdecl("_nitro_printing_call_printEscPos")
public func _nitro_printing_call_printEscPos(_ escPosData: UnsafeMutablePointer<UInt8>?, _ escPosData_length: Int64, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let escPosDataArr = escPosData.map { Data(UnsafeBufferPointer(start: $0, count: Int(escPosData_length))) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printEscPos(escPosData: escPosDataArr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:151
@_cdecl("_nitro_printing_call_printZpl")
public func _nitro_printing_call_printZpl(_ zpl: UnsafePointer<CChar>?, _ settings: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    let zplStr = zpl != nil ? String(cString: zpl!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printZpl(zpl: zplStr, settings: settings.map { $0.assumingMemoryBound(to: _PrintSettingsC.self).pointee.toSwift() })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrintResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PrintResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:157
@_cdecl("_nitro_printing_call_cancelRawPrint")
public func _nitro_printing_call_cancelRawPrint() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.cancelRawPrint()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:164
@_cdecl("_nitro_printing_call_getPrinterStatusDetail")
public func _nitro_printing_call_getPrinterStatusDetail(_ printerId: UnsafePointer<CChar>?, _ timeoutSeconds: Int64) -> UnsafeMutableRawPointer? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrinterStatusDetail? = nil
    Task.detached {
        result = try? await impl.getPrinterStatusDetail(printerId: printerIdStr, timeoutSeconds: timeoutSeconds)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PrinterStatusDetailC>.allocate(capacity: 1)
    ptr.initialize(to: _PrinterStatusDetailC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

@_cdecl("_nitro_printing_register_onPrintJobChanged_stream")
public func _nitro_printing_register_onPrintJobChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutableRawPointer?) -> Void
) {
    NitroPrintingRegistry._onPrintJobChangedCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrintJobChanged.sink { item in
            let ptr = UnsafeMutablePointer<_PrintJobUpdateC>.allocate(capacity: 1)
            ptr.initialize(to: _PrintJobUpdateC.fromSwift(item))
            emitCb(dartPort, UnsafeMutableRawPointer(ptr))
        }
}

@_cdecl("_nitro_printing_release_onPrintJobChanged_stream")
public func _nitro_printing_release_onPrintJobChanged_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrintJobChangedCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrintJobChangedCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_printing_register_onPrinterStatusChanged_stream")
public func _nitro_printing_register_onPrinterStatusChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutableRawPointer?) -> Void
) {
    NitroPrintingRegistry._onPrinterStatusChangedCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrinterStatusChanged.sink { item in
            let ptr = UnsafeMutablePointer<_PrinterStatusC>.allocate(capacity: 1)
            ptr.initialize(to: _PrinterStatusC.fromSwift(item))
            emitCb(dartPort, UnsafeMutableRawPointer(ptr))
        }
}

@_cdecl("_nitro_printing_release_onPrinterStatusChanged_stream")
public func _nitro_printing_release_onPrinterStatusChanged_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrinterStatusChangedCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrinterStatusChangedCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_printing_register_onPrinterDiscovered_stream")
public func _nitro_printing_register_onPrinterDiscovered_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutableRawPointer?) -> Void
) {
    NitroPrintingRegistry._onPrinterDiscoveredCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrinterDiscovered.sink { item in
            let ptr = UnsafeMutablePointer<_DiscoveredPrinterC>.allocate(capacity: 1)
            ptr.initialize(to: _DiscoveredPrinterC.fromSwift(item))
            emitCb(dartPort, UnsafeMutableRawPointer(ptr))
        }
}

@_cdecl("_nitro_printing_release_onPrinterDiscovered_stream")
public func _nitro_printing_release_onPrinterDiscovered_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrinterDiscoveredCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrinterDiscoveredCancellables.removeValue(forKey: dartPort)
}
