// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.4
// Generated from: nitro_printing.native.dart
part of 'nitro_printing.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension PrintStateNativeExt on PrintState {
  int get nativeValue => index + 0;
}

extension PrintStateFromNativeExt on int {
  PrintState toPrintState() => PrintState.values[this - 0];
}

extension PrintQualityNativeExt on PrintQuality {
  int get nativeValue => index + 0;
}

extension PrintQualityFromNativeExt on int {
  PrintQuality toPrintQuality() => PrintQuality.values[this - 0];
}

extension PaperSizeNativeExt on PaperSize {
  int get nativeValue => index + 0;
}

extension PaperSizeFromNativeExt on int {
  PaperSize toPaperSize() => PaperSize.values[this - 0];
}

extension DocumentTypeNativeExt on DocumentType {
  int get nativeValue => index + 0;
}

extension DocumentTypeFromNativeExt on int {
  DocumentType toDocumentType() => DocumentType.values[this - 0];
}

extension MediaTypeNativeExt on MediaType {
  int get nativeValue => index + 0;
}

extension MediaTypeFromNativeExt on int {
  MediaType toMediaType() => MediaType.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class PrintDocumentFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> title;
  @Int32()
  external int type;
  external Pointer<Uint8> data;
  @Int64()
  external int dataLength;
}

extension PrintDocumentFfiExt on PrintDocumentFfi {
  PrintDocument toDart() {
    return PrintDocument(
      id: id.toDartString(),
      title: title.toDartString(),
      type: type.toDocumentType(),
      data: Uint8List.fromList(data.asTypedList(dataLength)),
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (id != nullptr) {
      malloc.free(id);
    }
    if (title != nullptr) {
      malloc.free(title);
    }
    if (data != nullptr) {
      malloc.free(data);
    }
  }
}

extension PrintDocumentExt on PrintDocument {
  Pointer<PrintDocumentFfi> toNative(Arena arena) {
    final ptr = arena<PrintDocumentFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.title = title.toNativeUtf8(allocator: arena);
    ptr.ref.type = type.nativeValue;
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.dataLength = data.length;
    return ptr;
  }
}

final class PreviewResultFfi extends Struct {
  external Pointer<Uint8> bytes;
  @Int64()
  external int length;
}

extension PreviewResultFfiExt on PreviewResultFfi {
  PreviewResult toDart() {
    return PreviewResult(
      bytes: Uint8List.fromList(bytes.asTypedList(length)),
      length: length,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension PreviewResultExt on PreviewResult {
  Pointer<PreviewResultFfi> toNative(Arena arena) {
    final ptr = arena<PreviewResultFfi>();
    ptr.ref.bytes = bytes.toPointer(arena);
    ptr.ref.length = length;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [PrintDocument].
/// Extends [PrintDocument] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintDocumentProxy <: PrintDocument`, a `Stream<PrintDocumentProxy>`
/// satisfies `Stream<PrintDocument>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintDocument'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class PrintDocumentProxy extends PrintDocument implements Finalizable {
  final Pointer<PrintDocumentFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintDocument',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  PrintDocumentProxy(this._native)
    : super(
        id: '',
        title: '',
        type: DocumentType.values.first,
        data: Uint8List(0),
      ) {
    assert(
      _finalizer != null,
      'PrintDocumentProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get id => _native.ref.id.toDartString();
  @override
  String get title => _native.ref.title.toDartString();
  @override
  DocumentType get type => _native.ref.type.toDocumentType();
  @override
  Uint8List get data => _native.ref.data.asTypedList(_native.ref.dataLength);

  /// Eagerly copies all fields to a plain [PrintDocument] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintDocument toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PreviewResult].
/// Extends [PreviewResult] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PreviewResultProxy <: PreviewResult`, a `Stream<PreviewResultProxy>`
/// satisfies `Stream<PreviewResult>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PreviewResult'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class PreviewResultProxy extends PreviewResult implements Finalizable {
  final Pointer<PreviewResultFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PreviewResult',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  PreviewResultProxy(this._native) : super(bytes: Uint8List(0), length: 0) {
    assert(
      _finalizer != null,
      'PreviewResultProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get bytes => _native.ref.bytes.asTypedList(_native.ref.length);
  @override
  int get length => _native.ref.length;

  /// Eagerly copies all fields to a plain [PreviewResult] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PreviewResult toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension PrinterInfoRecordExt on PrinterInfo {
  static PrinterInfo fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrinterInfo fromReader(RecordReader r) => PrinterInfo(
    id: r.readString(),
    name: r.readString(),
    address: r.readString(),
    isDefault: r.readBool(),
    isAvailable: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeString(address);
    writer.writeBool(isDefault);
    writer.writeBool(isAvailable);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrinterCapabilitiesRecordExt on PrinterCapabilities {
  static PrinterCapabilities fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrinterCapabilities fromReader(RecordReader r) => PrinterCapabilities(
    supportsColor: r.readBool(),
    supportsDuplex: r.readBool(),
    supportsCopy: r.readBool(),
    maxCopies: r.readInt(),
    minMarginTop: r.readDouble(),
    minMarginBottom: r.readDouble(),
    minMarginLeft: r.readDouble(),
    minMarginRight: r.readDouble(),
    supportsA4: r.readBool(),
    supportsA5: r.readBool(),
    supportsLetter: r.readBool(),
    supportsLegal: r.readBool(),
    supportsDraftQuality: r.readBool(),
    supportsNormalQuality: r.readBool(),
    supportsHighQuality: r.readBool(),
    supportsBestQuality: r.readBool(),
    maxResolutionDpi: r.readInt(),
    supportsCustomPaper: r.readBool(),
    supportsBorderless: r.readBool(),
    inputTrays: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeBool(supportsColor);
    writer.writeBool(supportsDuplex);
    writer.writeBool(supportsCopy);
    writer.writeInt(maxCopies);
    writer.writeDouble(minMarginTop);
    writer.writeDouble(minMarginBottom);
    writer.writeDouble(minMarginLeft);
    writer.writeDouble(minMarginRight);
    writer.writeBool(supportsA4);
    writer.writeBool(supportsA5);
    writer.writeBool(supportsLetter);
    writer.writeBool(supportsLegal);
    writer.writeBool(supportsDraftQuality);
    writer.writeBool(supportsNormalQuality);
    writer.writeBool(supportsHighQuality);
    writer.writeBool(supportsBestQuality);
    writer.writeInt(maxResolutionDpi);
    writer.writeBool(supportsCustomPaper);
    writer.writeBool(supportsBorderless);
    writer.writeString(inputTrays);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrintSettingsRecordExt on PrintSettings {
  static PrintSettings fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrintSettings fromReader(RecordReader r) => PrintSettings(
    printerId: r.readString(),
    paperSize: r.readInt().toPaperSize(),
    orientationDegrees: r.readDouble(),
    quality: r.readInt().toPrintQuality(),
    copies: r.readInt(),
    collate: r.readBool(),
    duplex: r.readBool(),
    color: r.readBool(),
    marginTop: r.readDouble(),
    marginBottom: r.readDouble(),
    marginLeft: r.readDouble(),
    marginRight: r.readDouble(),
    jobName: r.readString(),
    pagesPerSheet: r.readInt(),
    showPrintDialog: r.readBool(),
    pageRangeFrom: r.readInt(),
    pageRangeTo: r.readInt(),
    customPaperWidth: r.readDouble(),
    customPaperHeight: r.readDouble(),
    fitToPage: r.readBool(),
    mediaType: r.readInt().toMediaType(),
    headerText: r.readString(),
    footerText: r.readString(),
    inputTray: r.readString(),
    networkTimeoutSeconds: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(printerId);
    writer.writeInt(paperSize.nativeValue);
    writer.writeDouble(orientationDegrees);
    writer.writeInt(quality.nativeValue);
    writer.writeInt(copies);
    writer.writeBool(collate);
    writer.writeBool(duplex);
    writer.writeBool(color);
    writer.writeDouble(marginTop);
    writer.writeDouble(marginBottom);
    writer.writeDouble(marginLeft);
    writer.writeDouble(marginRight);
    writer.writeString(jobName);
    writer.writeInt(pagesPerSheet);
    writer.writeBool(showPrintDialog);
    writer.writeInt(pageRangeFrom);
    writer.writeInt(pageRangeTo);
    writer.writeDouble(customPaperWidth);
    writer.writeDouble(customPaperHeight);
    writer.writeBool(fitToPage);
    writer.writeInt(mediaType.nativeValue);
    writer.writeString(headerText);
    writer.writeString(footerText);
    writer.writeString(inputTray);
    writer.writeInt(networkTimeoutSeconds);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrintJobRecordExt on PrintJob {
  static PrintJob fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrintJob fromReader(RecordReader r) => PrintJob(
    id: r.readString(),
    printerId: r.readString(),
    documentTitle: r.readString(),
    state: r.readInt().toPrintState(),
    progress: r.readInt(),
    createdAtMillis: r.readInt(),
    completedAtMillis: r.readInt(),
    errorMessage: r.readString(),
    pagesPrinted: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(printerId);
    writer.writeString(documentTitle);
    writer.writeInt(state.nativeValue);
    writer.writeInt(progress);
    writer.writeInt(createdAtMillis);
    writer.writeInt(completedAtMillis);
    writer.writeString(errorMessage);
    writer.writeInt(pagesPrinted);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrintResultRecordExt on PrintResult {
  static PrintResult fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrintResult fromReader(RecordReader r) => PrintResult(
    success: r.readBool(),
    jobId: r.readString(),
    errorMessage: r.readString(),
    errorCode: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeBool(success);
    writer.writeString(jobId);
    writer.writeString(errorMessage);
    writer.writeString(errorCode);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrintJobUpdateRecordExt on PrintJobUpdate {
  static PrintJobUpdate fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrintJobUpdate fromReader(RecordReader r) => PrintJobUpdate(
    jobId: r.readString(),
    state: r.readInt().toPrintState(),
    progress: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(jobId);
    writer.writeInt(state.nativeValue);
    writer.writeInt(progress);
    writer.writeString(message);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrinterStatusRecordExt on PrinterStatus {
  static PrinterStatus fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrinterStatus fromReader(RecordReader r) => PrinterStatus(
    printerId: r.readString(),
    isOnline: r.readBool(),
    isPrinting: r.readBool(),
    jobsInQueue: r.readInt(),
    statusMessage: r.readString(),
    inkLevel: r.readInt(),
    tonerLevel: r.readInt(),
    paperLevel: r.readInt(),
    errorCode: r.readString(),
    isWarmingUp: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(printerId);
    writer.writeBool(isOnline);
    writer.writeBool(isPrinting);
    writer.writeInt(jobsInQueue);
    writer.writeString(statusMessage);
    writer.writeInt(inkLevel);
    writer.writeInt(tonerLevel);
    writer.writeInt(paperLevel);
    writer.writeString(errorCode);
    writer.writeBool(isWarmingUp);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension DiscoveredPrinterRecordExt on DiscoveredPrinter {
  static DiscoveredPrinter fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static DiscoveredPrinter fromReader(RecordReader r) => DiscoveredPrinter(
    id: r.readString(),
    name: r.readString(),
    host: r.readString(),
    port: r.readInt(),
    serviceType: r.readString(),
    uri: r.readString(),
    isAvailable: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeString(host);
    writer.writeInt(port);
    writer.writeString(serviceType);
    writer.writeString(uri);
    writer.writeBool(isAvailable);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension PrinterStatusDetailRecordExt on PrinterStatusDetail {
  static PrinterStatusDetail fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrinterStatusDetail fromReader(RecordReader r) => PrinterStatusDetail(
    printerId: r.readString(),
    isOnline: r.readBool(),
    isReady: r.readBool(),
    hasPaperJam: r.readBool(),
    isOutOfPaper: r.readBool(),
    isOutOfInk: r.readBool(),
    inkLevelBlack: r.readInt(),
    inkLevelCyan: r.readInt(),
    inkLevelMagenta: r.readInt(),
    inkLevelYellow: r.readInt(),
    tonerLevel: r.readInt(),
    paperLevel: r.readInt(),
    jobsInQueue: r.readInt(),
    isWarmingUp: r.readBool(),
    printerState: r.readString(),
    stateReasons: r.readString(),
    statusMessage: r.readString(),
    errorCode: r.readString(),
    isDuplexSupported: r.readBool(),
    isColorSupported: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(printerId);
    writer.writeBool(isOnline);
    writer.writeBool(isReady);
    writer.writeBool(hasPaperJam);
    writer.writeBool(isOutOfPaper);
    writer.writeBool(isOutOfInk);
    writer.writeInt(inkLevelBlack);
    writer.writeInt(inkLevelCyan);
    writer.writeInt(inkLevelMagenta);
    writer.writeInt(inkLevelYellow);
    writer.writeInt(tonerLevel);
    writer.writeInt(paperLevel);
    writer.writeInt(jobsInQueue);
    writer.writeBool(isWarmingUp);
    writer.writeString(printerState);
    writer.writeString(stateReasons);
    writer.writeString(statusMessage);
    writer.writeString(errorCode);
    writer.writeBool(isDuplexSupported);
    writer.writeBool(isColorSupported);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _NitroPrintingImpl extends NitroPrinting {
  final DynamicLibrary _dylib;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_printing',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  _NitroPrintingImpl() : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_printing_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_printing: Dart API DL initialization failed with code $initCode.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_printing',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_printing_nitro_abi_version',
      )(),
    );
    NitroRuntime.checkLinkChecksum(
      'nitro_printing',
      '2cb1508886d0908a',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_printing_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    PrintDocumentProxy._init(_dylib);
    PreviewResultProxy._init(_dylib);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_printing)',
      'initialized in ${initSw.elapsedMicroseconds} µs',
    );
  }

  late final int Function(Pointer<NitroErrorFfi>) _isPrintingSupportedPtr =
      _dylib
          .lookup<NativeFunction<Int8 Function(Pointer<NitroErrorFfi>)>>(
            'nitro_printing_is_printing_supported',
          )
          .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getPrintersCountPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_printing_get_printers_count',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _getPrinterDriverVersionPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_printing_get_printer_driver_version');
  late final Pointer<Uint8> Function() _getAllPrintersPtr = _dylib
      .lookupFunction<Pointer<Uint8> Function(), Pointer<Uint8> Function()>(
        'nitro_printing_get_all_printers',
      );
  late final Pointer<Uint8> Function(int) _getPrinterAtPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64),
        Pointer<Uint8> Function(int)
      >('nitro_printing_get_printer_at');
  late final Pointer<Uint8> Function() _getDefaultPrinterPtr = _dylib
      .lookupFunction<Pointer<Uint8> Function(), Pointer<Uint8> Function()>(
        'nitro_printing_get_default_printer',
      );
  late final Pointer<Uint8> Function(Pointer<Utf8>) _getPrinterCapabilitiesPtr =
      _dylib.lookupFunction<
        Pointer<Uint8> Function(Pointer<Utf8>),
        Pointer<Uint8> Function(Pointer<Utf8>)
      >('nitro_printing_get_printer_capabilities');
  late final Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>)
  _printTextPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>)
      >('nitro_printing_print_text');
  late final Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
  _printImagePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Int64, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
      >('nitro_printing_print_image');
  late final Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
  _printPdfPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Int64, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
      >('nitro_printing_print_pdf');
  late final Pointer<Uint8> Function(Pointer<Void>, Pointer<Uint8>)
  _printDocumentPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Void>, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Void>, Pointer<Uint8>)
      >('nitro_printing_print_document');
  late final int Function(Pointer<Utf8>, Pointer<Uint8>) _printFilePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>, Pointer<Uint8>),
        int Function(Pointer<Utf8>, Pointer<Uint8>)
      >('nitro_printing_print_file');
  late final Pointer<Void> Function(Pointer<Void>, Pointer<Uint8>)
  _renderPreviewPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Void>, Pointer<Uint8>),
        Pointer<Void> Function(Pointer<Void>, Pointer<Uint8>)
      >('nitro_printing_render_preview');
  late final int Function(Pointer<Void>) _getPageCountPtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Void>),
        int Function(Pointer<Void>)
      >('nitro_printing_get_page_count');
  late final int Function(Pointer<Void>, Pointer<Utf8>, Pointer<Uint8>)
  _printToFilePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Void>, Pointer<Utf8>, Pointer<Uint8>),
        int Function(Pointer<Void>, Pointer<Utf8>, Pointer<Uint8>)
      >('nitro_printing_print_to_file');
  late final int Function(Pointer<Utf8>) _cancelPrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_cancel_print_job');
  late final int Function(Pointer<Utf8>) _pausePrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_pause_print_job');
  late final int Function(Pointer<Utf8>) _resumePrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_resume_print_job');
  late final int Function() _clearPrintQueuePtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_clear_print_queue',
      );
  late final int Function() _getPrintJobsCountPtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>(
        'nitro_printing_get_print_jobs_count',
      );
  late final Pointer<Uint8> Function(int) _getPrintJobAtPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64),
        Pointer<Uint8> Function(int)
      >('nitro_printing_get_print_job_at');
  late final Pointer<Uint8> Function(Pointer<Utf8>) _getPrintJobStatusPtr =
      _dylib.lookupFunction<
        Pointer<Uint8> Function(Pointer<Utf8>),
        Pointer<Uint8> Function(Pointer<Utf8>)
      >('nitro_printing_get_print_job_status');
  late final int Function() _startPrinterDiscoveryPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_start_printer_discovery',
      );
  late final int Function() _stopPrinterDiscoveryPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_stop_printer_discovery',
      );
  late final int Function(Pointer<Utf8>, int) _testPrinterConnectionPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>, Int64),
        int Function(Pointer<Utf8>, int)
      >('nitro_printing_test_printer_connection');
  late final int Function(Pointer<Utf8>) _setDefaultPrinterPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_set_default_printer');
  late final int Function(Pointer<Utf8>) _openSystemPrintQueuePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_open_system_print_queue');
  late final int Function(Pointer<Utf8>) _openPrinterPropertiesPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_open_printer_properties');
  late final Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
  _printRawPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Int64, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
      >('nitro_printing_print_raw');
  late final Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
  _printEscPosPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Int64, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<Uint8>)
      >('nitro_printing_print_esc_pos');
  late final Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>)
  _printZplPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Utf8>, Pointer<Uint8>)
      >('nitro_printing_print_zpl');
  late final int Function() _cancelRawPrintPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_cancel_raw_print',
      );
  late final Pointer<Uint8> Function(Pointer<Utf8>, int)
  _getPrinterStatusDetailPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Utf8>, Int64),
        Pointer<Uint8> Function(Pointer<Utf8>, int)
      >('nitro_printing_get_printer_status_detail');
  late final void Function(int) _registerOnPrintJobChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_print_job_changed_stream',
      );
  late final void Function(int) _releaseOnPrintJobChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_print_job_changed_stream',
      );
  late final void Function(int) _registerOnPrinterStatusChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_printer_status_changed_stream',
      );
  late final void Function(int) _releaseOnPrinterStatusChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_printer_status_changed_stream',
      );
  late final void Function(int) _registerOnPrinterDiscoveredPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_printer_discovered_stream',
      );
  late final void Function(int) _releaseOnPrinterDiscoveredPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_printer_discovered_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_printing_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_printing_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_printing_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_printing_clear_error');

  @override
  void dispose() {
    NitroRuntime.logLifecycle('dispose(nitro_printing)', 'disposing');
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_printing)', 'disposed');
  }

  @override
  bool isPrintingSupported() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _isPrintingSupportedPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res != 0;
    }, methodName: 'isPrintingSupported');
  }

  @override
  int getPrintersCount() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getPrintersCountPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'getPrintersCount');
  }

  @override
  String getPrinterDriverVersion(String printerId) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _getPrinterDriverVersionPtr(
          printerId.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        return res.toDartStringWithFree();
      }),
      methodName: 'getPrinterDriverVersion',
    );
  }

  @override
  Future<List<PrinterInfo>> getAllPrinters() async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _getAllPrintersPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getAllPrinters',
    );
    return LazyRecordList.decode(
      rawPtr,
      (r) => PrinterInfoRecordExt.fromReader(r),
    );
  }

  @override
  Future<PrinterInfo> getPrinterAt(int index) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _getPrinterAtPtr,
      [index],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getPrinterAt',
    );
    final PrinterInfo decoded;
    try {
      decoded = PrinterInfoRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  Future<PrinterInfo> getDefaultPrinter() async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _getDefaultPrinterPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getDefaultPrinter',
    );
    final PrinterInfo decoded;
    try {
      decoded = PrinterInfoRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  Future<PrinterCapabilities> getPrinterCapabilities(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _getPrinterCapabilitiesPtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPrinterCapabilities',
      );
      final PrinterCapabilities decoded;
      try {
        decoded = PrinterCapabilitiesRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printText(String text, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printTextPtr,
        [text.toNativeUtf8(allocator: arena), settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printText',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printImage(
    Uint8List imageData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printImagePtr,
        [
          imageData.toPointer(arena),
          imageData.length,
          settings.toNative(arena),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printImage',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printPdf(
    Uint8List pdfData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printPdfPtr,
        [pdfData.toPointer(arena), pdfData.length, settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printPdf',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printDocument(
    PrintDocument document, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printDocumentPtr,
        [document.toNative(arena).cast<Void>(), settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printDocument',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> printFile(String filePath, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _printFilePtr,
        [filePath.toNativeUtf8(allocator: arena), settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printFile',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PreviewResult> renderPreview(
    PrintDocument document, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _renderPreviewPtr,
        [document.toNative(arena).cast<Void>(), settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'renderPreview',
      );
      if (rawPtr == nullptr) {
        throw StateError('renderPreview returned null');
      }
      final structPtr = Pointer<PreviewResultFfi>.fromAddress(rawPtr.address);
      final PreviewResult decoded;
      try {
        decoded = structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<int> getPageCount(PrintDocument document) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _getPageCountPtr,
        [document.toNative(arena).cast<Void>()],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPageCount',
      );
      return res;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> printToFile(
    PrintDocument document,
    String outputPath, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _printToFilePtr,
        [
          document.toNative(arena).cast<Void>(),
          outputPath.toNativeUtf8(allocator: arena),
          settings.toNative(arena),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printToFile',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> cancelPrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _cancelPrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'cancelPrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> pausePrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _pausePrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'pausePrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> resumePrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _resumePrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'resumePrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> clearPrintQueue() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _clearPrintQueuePtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'clearPrintQueue',
    );
    return res != 0;
  }

  @override
  Future<int> getPrintJobsCount() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _getPrintJobsCountPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getPrintJobsCount',
    );
    return res;
  }

  @override
  Future<PrintJob> getPrintJobAt(int index) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
      _getPrintJobAtPtr,
      [index],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getPrintJobAt',
    );
    final PrintJob decoded;
    try {
      decoded = PrintJobRecordExt.fromNative(rawPtr);
    } finally {
      malloc.free(rawPtr);
    }
    return decoded;
  }

  @override
  Future<PrintJob> getPrintJobStatus(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _getPrintJobStatusPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPrintJobStatus',
      );
      final PrintJob decoded;
      try {
        decoded = PrintJobRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> startPrinterDiscovery() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _startPrinterDiscoveryPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'startPrinterDiscovery',
    );
    return res != 0;
  }

  @override
  Future<bool> stopPrinterDiscovery() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _stopPrinterDiscoveryPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'stopPrinterDiscovery',
    );
    return res != 0;
  }

  @override
  Future<bool> testPrinterConnection(
    String printerId, {
    int? timeoutSeconds,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _testPrinterConnectionPtr,
        [
          printerId.toNativeUtf8(allocator: arena),
          timeoutSeconds ?? -9223372036854775808,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'testPrinterConnection',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> setDefaultPrinter(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _setDefaultPrinterPtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'setDefaultPrinter',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> openSystemPrintQueue(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _openSystemPrintQueuePtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'openSystemPrintQueue',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> openPrinterProperties(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _openPrinterPropertiesPtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'openPrinterProperties',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printRaw(
    Uint8List data, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printRawPtr,
        [data.toPointer(arena), data.length, settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printRaw',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printEscPos(
    Uint8List escPosData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printEscPosPtr,
        [
          escPosData.toPointer(arena),
          escPosData.length,
          settings.toNative(arena),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printEscPos',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printZpl(String zpl, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _printZplPtr,
        [zpl.toNativeUtf8(allocator: arena), settings.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printZpl',
      );
      final PrintResult decoded;
      try {
        decoded = PrintResultRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> cancelRawPrint() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _cancelRawPrintPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'cancelRawPrint',
    );
    return res != 0;
  }

  @override
  Future<PrinterStatusDetail> getPrinterStatusDetail(
    String printerId, {
    int? timeoutSeconds,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _getPrinterStatusDetailPtr,
        [
          printerId.toNativeUtf8(allocator: arena),
          timeoutSeconds ?? -9223372036854775808,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPrinterStatusDetail',
      );
      final PrinterStatusDetail decoded;
      try {
        decoded = PrinterStatusDetailRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Stream<PrintJobUpdate> onPrintJobChanged() {
    checkDisposed();
    return NitroRuntime.openStream<PrintJobUpdate>(
      register: (port) => _registerOnPrintJobChangedPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrintJobChanged',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return PrintJobUpdateRecordExt.fromNative(rawPtr);
        } finally {
          malloc.free(rawPtr);
        }
      },
      release: (port) => _releaseOnPrintJobChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<PrinterStatus> onPrinterStatusChanged() {
    checkDisposed();
    return NitroRuntime.openStream<PrinterStatus>(
      register: (port) => _registerOnPrinterStatusChangedPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrinterStatusChanged',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return PrinterStatusRecordExt.fromNative(rawPtr);
        } finally {
          malloc.free(rawPtr);
        }
      },
      release: (port) => _releaseOnPrinterStatusChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<DiscoveredPrinter> onPrinterDiscovered() {
    checkDisposed();
    return NitroRuntime.openStream<DiscoveredPrinter>(
      register: (port) => _registerOnPrinterDiscoveredPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrinterDiscovered',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return DiscoveredPrinterRecordExt.fromNative(rawPtr);
        } finally {
          malloc.free(rawPtr);
        }
      },
      release: (port) => _releaseOnPrinterDiscoveredPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
