// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.3
// Generated from: nitro_printing.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_printing.native.dart';

// Web-split layout (this spec targets web): this part holds only the
// platform-neutral codecs. The dart:ffi implementation lives in
// generated/native/nitro_printing.ffi.g.dart; construct instances via the
// conditional factory in nitro_printing.platform.g.dart.

// --- Enum FFI helpers (generated by Nitrogen) ---

extension PrintStateNativeExt on PrintState {
  int get nativeValue => index + 0;
}

extension PrintStateFromNativeExt on int {
  PrintState toPrintState() => PrintState.values[this - 0];
}

extension PrintQualityNativeExt on PrintQuality {
  int get nativeValue => index + 0;
}

extension PrintQualityFromNativeExt on int {
  PrintQuality toPrintQuality() => PrintQuality.values[this - 0];
}

extension PaperSizeNativeExt on PaperSize {
  int get nativeValue => index + 0;
}

extension PaperSizeFromNativeExt on int {
  PaperSize toPaperSize() => PaperSize.values[this - 0];
}

extension DocumentTypeNativeExt on DocumentType {
  int get nativeValue => index + 0;
}

extension DocumentTypeFromNativeExt on int {
  DocumentType toDocumentType() => DocumentType.values[this - 0];
}

extension MediaTypeNativeExt on MediaType {
  int get nativeValue => index + 0;
}

extension MediaTypeFromNativeExt on int {
  MediaType toMediaType() => MediaType.values[this - 0];
}

extension PrintDialogStateNativeExt on PrintDialogState {
  int get nativeValue => index + 0;
}

extension PrintDialogStateFromNativeExt on int {
  PrintDialogState toPrintDialogState() => PrintDialogState.values[this - 0];
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension PrinterInfoRecordExt on PrinterInfo {
  static PrinterInfo fromReader(RecordReaderBase r) => PrinterInfo(
    id: r.readString(),
    name: r.readString(),
    address: r.readString(),
    isDefault: r.readBool(),
    isAvailable: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeString(address);
    writer.writeBool(isDefault);
    writer.writeBool(isAvailable);
  }
}

extension PrinterCapabilitiesRecordExt on PrinterCapabilities {
  static PrinterCapabilities fromReader(RecordReaderBase r) =>
      PrinterCapabilities(
        supportsColor: r.readBool(),
        supportsDuplex: r.readBool(),
        supportsCopy: r.readBool(),
        maxCopies: r.readInt(),
        minMarginTop: r.readDouble(),
        minMarginBottom: r.readDouble(),
        minMarginLeft: r.readDouble(),
        minMarginRight: r.readDouble(),
        supportsA4: r.readBool(),
        supportsA5: r.readBool(),
        supportsLetter: r.readBool(),
        supportsLegal: r.readBool(),
        supportsDraftQuality: r.readBool(),
        supportsNormalQuality: r.readBool(),
        supportsHighQuality: r.readBool(),
        supportsBestQuality: r.readBool(),
        maxResolutionDpi: r.readInt(),
        supportsCustomPaper: r.readBool(),
        supportsBorderless: r.readBool(),
        inputTrays: r.readString(),
      );

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(supportsColor);
    writer.writeBool(supportsDuplex);
    writer.writeBool(supportsCopy);
    writer.writeInt(maxCopies);
    writer.writeDouble(minMarginTop);
    writer.writeDouble(minMarginBottom);
    writer.writeDouble(minMarginLeft);
    writer.writeDouble(minMarginRight);
    writer.writeBool(supportsA4);
    writer.writeBool(supportsA5);
    writer.writeBool(supportsLetter);
    writer.writeBool(supportsLegal);
    writer.writeBool(supportsDraftQuality);
    writer.writeBool(supportsNormalQuality);
    writer.writeBool(supportsHighQuality);
    writer.writeBool(supportsBestQuality);
    writer.writeInt(maxResolutionDpi);
    writer.writeBool(supportsCustomPaper);
    writer.writeBool(supportsBorderless);
    writer.writeString(inputTrays);
  }
}

extension PrintSettingsRecordExt on PrintSettings {
  static PrintSettings fromReader(RecordReaderBase r) => PrintSettings(
    printerId: r.readString(),
    paperSize: r.readInt().toPaperSize(),
    orientationDegrees: r.readDouble(),
    quality: r.readInt().toPrintQuality(),
    copies: r.readInt(),
    collate: r.readBool(),
    duplex: r.readBool(),
    color: r.readBool(),
    marginTop: r.readDouble(),
    marginBottom: r.readDouble(),
    marginLeft: r.readDouble(),
    marginRight: r.readDouble(),
    jobName: r.readString(),
    pagesPerSheet: r.readInt(),
    showPrintDialog: r.readBool(),
    pageRangeFrom: r.readInt(),
    pageRangeTo: r.readInt(),
    customPaperWidth: r.readDouble(),
    customPaperHeight: r.readDouble(),
    fitToPage: r.readBool(),
    mediaType: r.readInt().toMediaType(),
    headerText: r.readString(),
    footerText: r.readString(),
    inputTray: r.readString(),
    networkTimeoutSeconds: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(printerId);
    writer.writeInt(paperSize.nativeValue);
    writer.writeDouble(orientationDegrees);
    writer.writeInt(quality.nativeValue);
    writer.writeInt(copies);
    writer.writeBool(collate);
    writer.writeBool(duplex);
    writer.writeBool(color);
    writer.writeDouble(marginTop);
    writer.writeDouble(marginBottom);
    writer.writeDouble(marginLeft);
    writer.writeDouble(marginRight);
    writer.writeString(jobName);
    writer.writeInt(pagesPerSheet);
    writer.writeBool(showPrintDialog);
    writer.writeInt(pageRangeFrom);
    writer.writeInt(pageRangeTo);
    writer.writeDouble(customPaperWidth);
    writer.writeDouble(customPaperHeight);
    writer.writeBool(fitToPage);
    writer.writeInt(mediaType.nativeValue);
    writer.writeString(headerText);
    writer.writeString(footerText);
    writer.writeString(inputTray);
    writer.writeInt(networkTimeoutSeconds);
  }
}

extension PrintDocumentRecordExt on PrintDocument {
  static PrintDocument fromReader(RecordReaderBase r) => PrintDocument(
    id: r.readString(),
    title: r.readString(),
    type: r.readInt().toDocumentType(),
    data: r.readBlob(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(id);
    writer.writeString(title);
    writer.writeInt(type.nativeValue);
    writer.writeBlob(data);
  }
}

extension PrintJobRecordExt on PrintJob {
  static PrintJob fromReader(RecordReaderBase r) => PrintJob(
    id: r.readString(),
    printerId: r.readString(),
    documentTitle: r.readString(),
    state: r.readInt().toPrintState(),
    progress: r.readInt(),
    createdAtMillis: r.readInt(),
    completedAtMillis: r.readInt(),
    errorMessage: r.readString(),
    pagesPrinted: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(id);
    writer.writeString(printerId);
    writer.writeString(documentTitle);
    writer.writeInt(state.nativeValue);
    writer.writeInt(progress);
    writer.writeInt(createdAtMillis);
    writer.writeInt(completedAtMillis);
    writer.writeString(errorMessage);
    writer.writeInt(pagesPrinted);
  }
}

extension PrintResultRecordExt on PrintResult {
  static PrintResult fromReader(RecordReaderBase r) => PrintResult(
    success: r.readBool(),
    jobId: r.readString(),
    errorMessage: r.readString(),
    errorCode: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(success);
    writer.writeString(jobId);
    writer.writeString(errorMessage);
    writer.writeString(errorCode);
  }
}

extension PrintDialogResultRecordExt on PrintDialogResult {
  static PrintDialogResult fromReader(RecordReaderBase r) => PrintDialogResult(
    confirmed: r.readBool(),
    confirmedSettings: PrintSettingsRecordExt.fromReader(r),
    errorMessage: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBool(confirmed);
    confirmedSettings.writeFields(writer);
    writer.writeString(errorMessage);
  }
}

extension PrintJobUpdateRecordExt on PrintJobUpdate {
  static PrintJobUpdate fromReader(RecordReaderBase r) => PrintJobUpdate(
    jobId: r.readString(),
    state: r.readInt().toPrintState(),
    progress: r.readInt(),
    message: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(jobId);
    writer.writeInt(state.nativeValue);
    writer.writeInt(progress);
    writer.writeString(message);
  }
}

extension PrinterStatusRecordExt on PrinterStatus {
  static PrinterStatus fromReader(RecordReaderBase r) => PrinterStatus(
    printerId: r.readString(),
    isOnline: r.readBool(),
    isPrinting: r.readBool(),
    jobsInQueue: r.readInt(),
    statusMessage: r.readString(),
    inkLevel: r.readInt(),
    tonerLevel: r.readInt(),
    paperLevel: r.readInt(),
    errorCode: r.readString(),
    isWarmingUp: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(printerId);
    writer.writeBool(isOnline);
    writer.writeBool(isPrinting);
    writer.writeInt(jobsInQueue);
    writer.writeString(statusMessage);
    writer.writeInt(inkLevel);
    writer.writeInt(tonerLevel);
    writer.writeInt(paperLevel);
    writer.writeString(errorCode);
    writer.writeBool(isWarmingUp);
  }
}

extension DiscoveredPrinterRecordExt on DiscoveredPrinter {
  static DiscoveredPrinter fromReader(RecordReaderBase r) => DiscoveredPrinter(
    id: r.readString(),
    name: r.readString(),
    host: r.readString(),
    port: r.readInt(),
    serviceType: r.readString(),
    uri: r.readString(),
    isAvailable: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeString(host);
    writer.writeInt(port);
    writer.writeString(serviceType);
    writer.writeString(uri);
    writer.writeBool(isAvailable);
  }
}

extension PrinterStatusDetailRecordExt on PrinterStatusDetail {
  static PrinterStatusDetail fromReader(RecordReaderBase r) =>
      PrinterStatusDetail(
        printerId: r.readString(),
        isOnline: r.readBool(),
        isReady: r.readBool(),
        hasPaperJam: r.readBool(),
        isOutOfPaper: r.readBool(),
        isOutOfInk: r.readBool(),
        inkLevelBlack: r.readInt(),
        inkLevelCyan: r.readInt(),
        inkLevelMagenta: r.readInt(),
        inkLevelYellow: r.readInt(),
        tonerLevel: r.readInt(),
        paperLevel: r.readInt(),
        jobsInQueue: r.readInt(),
        isWarmingUp: r.readBool(),
        printerState: r.readString(),
        stateReasons: r.readString(),
        statusMessage: r.readString(),
        errorCode: r.readString(),
        isDuplexSupported: r.readBool(),
        isColorSupported: r.readBool(),
      );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(printerId);
    writer.writeBool(isOnline);
    writer.writeBool(isReady);
    writer.writeBool(hasPaperJam);
    writer.writeBool(isOutOfPaper);
    writer.writeBool(isOutOfInk);
    writer.writeInt(inkLevelBlack);
    writer.writeInt(inkLevelCyan);
    writer.writeInt(inkLevelMagenta);
    writer.writeInt(inkLevelYellow);
    writer.writeInt(tonerLevel);
    writer.writeInt(paperLevel);
    writer.writeInt(jobsInQueue);
    writer.writeBool(isWarmingUp);
    writer.writeString(printerState);
    writer.writeString(stateReasons);
    writer.writeString(statusMessage);
    writer.writeString(errorCode);
    writer.writeBool(isDuplexSupported);
    writer.writeBool(isColorSupported);
  }
}
