// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.5
// Generated from: nitro_printing.native.dart
// spec-sha256: 69815b3b61dd7cfb2fd141872f0b07b0de7933e4e25a8c9748563fe923a7b802
/// Platform-conditional factory for [NitroPrinting]:
///
/// ```dart
/// import 'nitro_printing.platform.g.dart';
///
/// await ensureNitroPrintingReady();               // no-op on native
/// final api = createNitroPrintingInstance();
/// ```
library;

export 'generated/native/nitro_printing.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_printing.web.bridge.g.dart'
    show createNitroPrintingInstance, ensureNitroPrintingReady;
