// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.1
// Generated from: nitro_printing.native.dart
/// Platform-conditional factory for [NitroPrinting]:
///
/// ```dart
/// import 'nitro_printing.platform.g.dart';
///
/// await ensureNitroPrintingReady();               // no-op on native
/// final api = createNitroPrintingInstance();
/// ```
library;

export 'generated/native/nitro_printing.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_printing.web.bridge.g.dart'
    show createNitroPrintingInstance, ensureNitroPrintingReady;
