// Generated by Nitrogen Modules. Do not edit.
// Generated from: nitro_printing.native.dart
part of 'nitro_printing.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension PrintStateNativeExt on PrintState {
  int get nativeValue => index + 0;
}

extension PrintStateFromNativeExt on int {
  PrintState toPrintState() => PrintState.values[this - 0];
}

extension PrintQualityNativeExt on PrintQuality {
  int get nativeValue => index + 0;
}

extension PrintQualityFromNativeExt on int {
  PrintQuality toPrintQuality() => PrintQuality.values[this - 0];
}

extension PaperSizeNativeExt on PaperSize {
  int get nativeValue => index + 0;
}

extension PaperSizeFromNativeExt on int {
  PaperSize toPaperSize() => PaperSize.values[this - 0];
}

extension DocumentTypeNativeExt on DocumentType {
  int get nativeValue => index + 0;
}

extension DocumentTypeFromNativeExt on int {
  DocumentType toDocumentType() => DocumentType.values[this - 0];
}

extension MediaTypeNativeExt on MediaType {
  int get nativeValue => index + 0;
}

extension MediaTypeFromNativeExt on int {
  MediaType toMediaType() => MediaType.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class PrinterInfoFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> name;
  external Pointer<Utf8> address;
  @Int8()
  external int isDefault;
  @Int8()
  external int isAvailable;
}

extension PrinterInfoFfiExt on PrinterInfoFfi {
  PrinterInfo toDart() {
    return PrinterInfo(
      id: id.toDartString(),
      name: name.toDartString(),
      address: address.toDartString(),
      isDefault: isDefault != 0,
      isAvailable: isAvailable != 0,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (id != nullptr) {
      malloc.free(id);
    }
    if (name != nullptr) {
      malloc.free(name);
    }
    if (address != nullptr) {
      malloc.free(address);
    }
  }
}

extension PrinterInfoExt on PrinterInfo {
  Pointer<PrinterInfoFfi> toNative(Arena arena) {
    final ptr = arena<PrinterInfoFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.name = name.toNativeUtf8(allocator: arena);
    ptr.ref.address = address.toNativeUtf8(allocator: arena);
    ptr.ref.isDefault = isDefault ? 1 : 0;
    ptr.ref.isAvailable = isAvailable ? 1 : 0;
    return ptr;
  }
}

final class PrinterCapabilitiesFfi extends Struct {
  @Int8()
  external int supportsColor;
  @Int8()
  external int supportsDuplex;
  @Int8()
  external int supportsCopy;
  @Int64()
  external int maxCopies;
  @Double()
  external double minMarginTop;
  @Double()
  external double minMarginBottom;
  @Double()
  external double minMarginLeft;
  @Double()
  external double minMarginRight;
  @Int8()
  external int supportsA4;
  @Int8()
  external int supportsA5;
  @Int8()
  external int supportsLetter;
  @Int8()
  external int supportsLegal;
  @Int8()
  external int supportsDraftQuality;
  @Int8()
  external int supportsNormalQuality;
  @Int8()
  external int supportsHighQuality;
  @Int8()
  external int supportsBestQuality;
  @Int64()
  external int maxResolutionDpi;
  @Int8()
  external int supportsCustomPaper;
  @Int8()
  external int supportsBorderless;
  external Pointer<Utf8> inputTrays;
}

extension PrinterCapabilitiesFfiExt on PrinterCapabilitiesFfi {
  PrinterCapabilities toDart() {
    return PrinterCapabilities(
      supportsColor: supportsColor != 0,
      supportsDuplex: supportsDuplex != 0,
      supportsCopy: supportsCopy != 0,
      maxCopies: maxCopies,
      minMarginTop: minMarginTop,
      minMarginBottom: minMarginBottom,
      minMarginLeft: minMarginLeft,
      minMarginRight: minMarginRight,
      supportsA4: supportsA4 != 0,
      supportsA5: supportsA5 != 0,
      supportsLetter: supportsLetter != 0,
      supportsLegal: supportsLegal != 0,
      supportsDraftQuality: supportsDraftQuality != 0,
      supportsNormalQuality: supportsNormalQuality != 0,
      supportsHighQuality: supportsHighQuality != 0,
      supportsBestQuality: supportsBestQuality != 0,
      maxResolutionDpi: maxResolutionDpi,
      supportsCustomPaper: supportsCustomPaper != 0,
      supportsBorderless: supportsBorderless != 0,
      inputTrays: inputTrays.toDartString(),
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (inputTrays != nullptr) {
      malloc.free(inputTrays);
    }
  }
}

extension PrinterCapabilitiesExt on PrinterCapabilities {
  Pointer<PrinterCapabilitiesFfi> toNative(Arena arena) {
    final ptr = arena<PrinterCapabilitiesFfi>();
    ptr.ref.supportsColor = supportsColor ? 1 : 0;
    ptr.ref.supportsDuplex = supportsDuplex ? 1 : 0;
    ptr.ref.supportsCopy = supportsCopy ? 1 : 0;
    ptr.ref.maxCopies = maxCopies;
    ptr.ref.minMarginTop = minMarginTop;
    ptr.ref.minMarginBottom = minMarginBottom;
    ptr.ref.minMarginLeft = minMarginLeft;
    ptr.ref.minMarginRight = minMarginRight;
    ptr.ref.supportsA4 = supportsA4 ? 1 : 0;
    ptr.ref.supportsA5 = supportsA5 ? 1 : 0;
    ptr.ref.supportsLetter = supportsLetter ? 1 : 0;
    ptr.ref.supportsLegal = supportsLegal ? 1 : 0;
    ptr.ref.supportsDraftQuality = supportsDraftQuality ? 1 : 0;
    ptr.ref.supportsNormalQuality = supportsNormalQuality ? 1 : 0;
    ptr.ref.supportsHighQuality = supportsHighQuality ? 1 : 0;
    ptr.ref.supportsBestQuality = supportsBestQuality ? 1 : 0;
    ptr.ref.maxResolutionDpi = maxResolutionDpi;
    ptr.ref.supportsCustomPaper = supportsCustomPaper ? 1 : 0;
    ptr.ref.supportsBorderless = supportsBorderless ? 1 : 0;
    ptr.ref.inputTrays = inputTrays.toNativeUtf8(allocator: arena);
    return ptr;
  }
}

final class PrintSettingsFfi extends Struct {
  external Pointer<Utf8> printerId;
  @Int32()
  external int paperSize;
  @Double()
  external double orientationDegrees;
  @Int32()
  external int quality;
  @Int64()
  external int copies;
  @Int8()
  external int collate;
  @Int8()
  external int duplex;
  @Int8()
  external int color;
  @Double()
  external double marginTop;
  @Double()
  external double marginBottom;
  @Double()
  external double marginLeft;
  @Double()
  external double marginRight;
  external Pointer<Utf8> jobName;
  @Int64()
  external int pagesPerSheet;
  @Int8()
  external int showPrintDialog;
  @Int64()
  external int pageRangeFrom;
  @Int64()
  external int pageRangeTo;
  @Double()
  external double customPaperWidth;
  @Double()
  external double customPaperHeight;
  @Int8()
  external int fitToPage;
  @Int32()
  external int mediaType;
  external Pointer<Utf8> headerText;
  external Pointer<Utf8> footerText;
  external Pointer<Utf8> inputTray;
  @Int64()
  external int networkTimeoutSeconds;
}

extension PrintSettingsFfiExt on PrintSettingsFfi {
  PrintSettings toDart() {
    return PrintSettings(
      printerId: printerId.toDartString(),
      paperSize: paperSize.toPaperSize(),
      orientationDegrees: orientationDegrees,
      quality: quality.toPrintQuality(),
      copies: copies,
      collate: collate != 0,
      duplex: duplex != 0,
      color: color != 0,
      marginTop: marginTop,
      marginBottom: marginBottom,
      marginLeft: marginLeft,
      marginRight: marginRight,
      jobName: jobName.toDartString(),
      pagesPerSheet: pagesPerSheet,
      showPrintDialog: showPrintDialog != 0,
      pageRangeFrom: pageRangeFrom,
      pageRangeTo: pageRangeTo,
      customPaperWidth: customPaperWidth,
      customPaperHeight: customPaperHeight,
      fitToPage: fitToPage != 0,
      mediaType: mediaType.toMediaType(),
      headerText: headerText.toDartString(),
      footerText: footerText.toDartString(),
      inputTray: inputTray.toDartString(),
      networkTimeoutSeconds: networkTimeoutSeconds,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (printerId != nullptr) {
      malloc.free(printerId);
    }
    if (jobName != nullptr) {
      malloc.free(jobName);
    }
    if (headerText != nullptr) {
      malloc.free(headerText);
    }
    if (footerText != nullptr) {
      malloc.free(footerText);
    }
    if (inputTray != nullptr) {
      malloc.free(inputTray);
    }
  }
}

extension PrintSettingsExt on PrintSettings {
  Pointer<PrintSettingsFfi> toNative(Arena arena) {
    final ptr = arena<PrintSettingsFfi>();
    ptr.ref.printerId = printerId.toNativeUtf8(allocator: arena);
    ptr.ref.paperSize = paperSize.nativeValue;
    ptr.ref.orientationDegrees = orientationDegrees;
    ptr.ref.quality = quality.nativeValue;
    ptr.ref.copies = copies;
    ptr.ref.collate = collate ? 1 : 0;
    ptr.ref.duplex = duplex ? 1 : 0;
    ptr.ref.color = color ? 1 : 0;
    ptr.ref.marginTop = marginTop;
    ptr.ref.marginBottom = marginBottom;
    ptr.ref.marginLeft = marginLeft;
    ptr.ref.marginRight = marginRight;
    ptr.ref.jobName = jobName.toNativeUtf8(allocator: arena);
    ptr.ref.pagesPerSheet = pagesPerSheet;
    ptr.ref.showPrintDialog = showPrintDialog ? 1 : 0;
    ptr.ref.pageRangeFrom = pageRangeFrom;
    ptr.ref.pageRangeTo = pageRangeTo;
    ptr.ref.customPaperWidth = customPaperWidth;
    ptr.ref.customPaperHeight = customPaperHeight;
    ptr.ref.fitToPage = fitToPage ? 1 : 0;
    ptr.ref.mediaType = mediaType.nativeValue;
    ptr.ref.headerText = headerText.toNativeUtf8(allocator: arena);
    ptr.ref.footerText = footerText.toNativeUtf8(allocator: arena);
    ptr.ref.inputTray = inputTray.toNativeUtf8(allocator: arena);
    ptr.ref.networkTimeoutSeconds = networkTimeoutSeconds;
    return ptr;
  }
}

final class PrintDocumentFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> title;
  @Int32()
  external int type;
  external Pointer<Uint8> data;
  @Int64()
  external int dataLength;
}

extension PrintDocumentFfiExt on PrintDocumentFfi {
  PrintDocument toDart() {
    return PrintDocument(
      id: id.toDartString(),
      title: title.toDartString(),
      type: type.toDocumentType(),
      data: Uint8List.fromList(data.asTypedList(dataLength)),
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (id != nullptr) {
      malloc.free(id);
    }
    if (title != nullptr) {
      malloc.free(title);
    }
    if (data != nullptr) {
      malloc.free(data);
    }
  }
}

extension PrintDocumentExt on PrintDocument {
  Pointer<PrintDocumentFfi> toNative(Arena arena) {
    final ptr = arena<PrintDocumentFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.title = title.toNativeUtf8(allocator: arena);
    ptr.ref.type = type.nativeValue;
    ptr.ref.data = data.toPointer(arena);
    ptr.ref.dataLength = data.length;
    return ptr;
  }
}

final class PrintJobFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> printerId;
  external Pointer<Utf8> documentTitle;
  @Int32()
  external int state;
  @Int64()
  external int progress;
  @Int64()
  external int createdAtMillis;
  @Int64()
  external int completedAtMillis;
  external Pointer<Utf8> errorMessage;
  @Int64()
  external int pagesPrinted;
}

extension PrintJobFfiExt on PrintJobFfi {
  PrintJob toDart() {
    return PrintJob(
      id: id.toDartString(),
      printerId: printerId.toDartString(),
      documentTitle: documentTitle.toDartString(),
      state: state.toPrintState(),
      progress: progress,
      createdAtMillis: createdAtMillis,
      completedAtMillis: completedAtMillis,
      errorMessage: errorMessage.toDartString(),
      pagesPrinted: pagesPrinted,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (id != nullptr) {
      malloc.free(id);
    }
    if (printerId != nullptr) {
      malloc.free(printerId);
    }
    if (documentTitle != nullptr) {
      malloc.free(documentTitle);
    }
    if (errorMessage != nullptr) {
      malloc.free(errorMessage);
    }
  }
}

extension PrintJobExt on PrintJob {
  Pointer<PrintJobFfi> toNative(Arena arena) {
    final ptr = arena<PrintJobFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.printerId = printerId.toNativeUtf8(allocator: arena);
    ptr.ref.documentTitle = documentTitle.toNativeUtf8(allocator: arena);
    ptr.ref.state = state.nativeValue;
    ptr.ref.progress = progress;
    ptr.ref.createdAtMillis = createdAtMillis;
    ptr.ref.completedAtMillis = completedAtMillis;
    ptr.ref.errorMessage = errorMessage.toNativeUtf8(allocator: arena);
    ptr.ref.pagesPrinted = pagesPrinted;
    return ptr;
  }
}

final class PrintResultFfi extends Struct {
  @Int8()
  external int success;
  external Pointer<Utf8> jobId;
  external Pointer<Utf8> errorMessage;
  external Pointer<Utf8> errorCode;
}

extension PrintResultFfiExt on PrintResultFfi {
  PrintResult toDart() {
    return PrintResult(
      success: success != 0,
      jobId: jobId.toDartString(),
      errorMessage: errorMessage.toDartString(),
      errorCode: errorCode.toDartString(),
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (jobId != nullptr) {
      malloc.free(jobId);
    }
    if (errorMessage != nullptr) {
      malloc.free(errorMessage);
    }
    if (errorCode != nullptr) {
      malloc.free(errorCode);
    }
  }
}

extension PrintResultExt on PrintResult {
  Pointer<PrintResultFfi> toNative(Arena arena) {
    final ptr = arena<PrintResultFfi>();
    ptr.ref.success = success ? 1 : 0;
    ptr.ref.jobId = jobId.toNativeUtf8(allocator: arena);
    ptr.ref.errorMessage = errorMessage.toNativeUtf8(allocator: arena);
    ptr.ref.errorCode = errorCode.toNativeUtf8(allocator: arena);
    return ptr;
  }
}

final class PrintJobUpdateFfi extends Struct {
  external Pointer<Utf8> jobId;
  @Int32()
  external int state;
  @Int64()
  external int progress;
  external Pointer<Utf8> message;
}

extension PrintJobUpdateFfiExt on PrintJobUpdateFfi {
  PrintJobUpdate toDart() {
    return PrintJobUpdate(
      jobId: jobId.toDartString(),
      state: state.toPrintState(),
      progress: progress,
      message: message.toDartString(),
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (jobId != nullptr) {
      malloc.free(jobId);
    }
    if (message != nullptr) {
      malloc.free(message);
    }
  }
}

extension PrintJobUpdateExt on PrintJobUpdate {
  Pointer<PrintJobUpdateFfi> toNative(Arena arena) {
    final ptr = arena<PrintJobUpdateFfi>();
    ptr.ref.jobId = jobId.toNativeUtf8(allocator: arena);
    ptr.ref.state = state.nativeValue;
    ptr.ref.progress = progress;
    ptr.ref.message = message.toNativeUtf8(allocator: arena);
    return ptr;
  }
}

final class PrinterStatusFfi extends Struct {
  external Pointer<Utf8> printerId;
  @Int8()
  external int isOnline;
  @Int8()
  external int isPrinting;
  @Int64()
  external int jobsInQueue;
  external Pointer<Utf8> statusMessage;
  @Int64()
  external int inkLevel;
  @Int64()
  external int tonerLevel;
  @Int64()
  external int paperLevel;
  external Pointer<Utf8> errorCode;
  @Int8()
  external int isWarmingUp;
}

extension PrinterStatusFfiExt on PrinterStatusFfi {
  PrinterStatus toDart() {
    return PrinterStatus(
      printerId: printerId.toDartString(),
      isOnline: isOnline != 0,
      isPrinting: isPrinting != 0,
      jobsInQueue: jobsInQueue,
      statusMessage: statusMessage.toDartString(),
      inkLevel: inkLevel,
      tonerLevel: tonerLevel,
      paperLevel: paperLevel,
      errorCode: errorCode.toDartString(),
      isWarmingUp: isWarmingUp != 0,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (printerId != nullptr) {
      malloc.free(printerId);
    }
    if (statusMessage != nullptr) {
      malloc.free(statusMessage);
    }
    if (errorCode != nullptr) {
      malloc.free(errorCode);
    }
  }
}

extension PrinterStatusExt on PrinterStatus {
  Pointer<PrinterStatusFfi> toNative(Arena arena) {
    final ptr = arena<PrinterStatusFfi>();
    ptr.ref.printerId = printerId.toNativeUtf8(allocator: arena);
    ptr.ref.isOnline = isOnline ? 1 : 0;
    ptr.ref.isPrinting = isPrinting ? 1 : 0;
    ptr.ref.jobsInQueue = jobsInQueue;
    ptr.ref.statusMessage = statusMessage.toNativeUtf8(allocator: arena);
    ptr.ref.inkLevel = inkLevel;
    ptr.ref.tonerLevel = tonerLevel;
    ptr.ref.paperLevel = paperLevel;
    ptr.ref.errorCode = errorCode.toNativeUtf8(allocator: arena);
    ptr.ref.isWarmingUp = isWarmingUp ? 1 : 0;
    return ptr;
  }
}

final class PreviewResultFfi extends Struct {
  external Pointer<Uint8> bytes;
  @Int64()
  external int length;
}

extension PreviewResultFfiExt on PreviewResultFfi {
  PreviewResult toDart() {
    return PreviewResult(
      bytes: Uint8List.fromList(bytes.asTypedList(length)),
      length: length,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension PreviewResultExt on PreviewResult {
  Pointer<PreviewResultFfi> toNative(Arena arena) {
    final ptr = arena<PreviewResultFfi>();
    ptr.ref.bytes = bytes.toPointer(arena);
    ptr.ref.length = length;
    return ptr;
  }
}

final class DiscoveredPrinterFfi extends Struct {
  external Pointer<Utf8> id;
  external Pointer<Utf8> name;
  external Pointer<Utf8> host;
  @Int64()
  external int port;
  external Pointer<Utf8> serviceType;
  external Pointer<Utf8> uri;
  @Int8()
  external int isAvailable;
}

extension DiscoveredPrinterFfiExt on DiscoveredPrinterFfi {
  DiscoveredPrinter toDart() {
    return DiscoveredPrinter(
      id: id.toDartString(),
      name: name.toDartString(),
      host: host.toDartString(),
      port: port,
      serviceType: serviceType.toDartString(),
      uri: uri.toDartString(),
      isAvailable: isAvailable != 0,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (id != nullptr) {
      malloc.free(id);
    }
    if (name != nullptr) {
      malloc.free(name);
    }
    if (host != nullptr) {
      malloc.free(host);
    }
    if (serviceType != nullptr) {
      malloc.free(serviceType);
    }
    if (uri != nullptr) {
      malloc.free(uri);
    }
  }
}

extension DiscoveredPrinterExt on DiscoveredPrinter {
  Pointer<DiscoveredPrinterFfi> toNative(Arena arena) {
    final ptr = arena<DiscoveredPrinterFfi>();
    ptr.ref.id = id.toNativeUtf8(allocator: arena);
    ptr.ref.name = name.toNativeUtf8(allocator: arena);
    ptr.ref.host = host.toNativeUtf8(allocator: arena);
    ptr.ref.port = port;
    ptr.ref.serviceType = serviceType.toNativeUtf8(allocator: arena);
    ptr.ref.uri = uri.toNativeUtf8(allocator: arena);
    ptr.ref.isAvailable = isAvailable ? 1 : 0;
    return ptr;
  }
}

final class PrinterStatusDetailFfi extends Struct {
  external Pointer<Utf8> printerId;
  @Int8()
  external int isOnline;
  @Int8()
  external int isReady;
  @Int8()
  external int hasPaperJam;
  @Int8()
  external int isOutOfPaper;
  @Int8()
  external int isOutOfInk;
  @Int64()
  external int inkLevelBlack;
  @Int64()
  external int inkLevelCyan;
  @Int64()
  external int inkLevelMagenta;
  @Int64()
  external int inkLevelYellow;
  @Int64()
  external int tonerLevel;
  @Int64()
  external int paperLevel;
  @Int64()
  external int jobsInQueue;
  @Int8()
  external int isWarmingUp;
  external Pointer<Utf8> printerState;
  external Pointer<Utf8> stateReasons;
  external Pointer<Utf8> statusMessage;
  external Pointer<Utf8> errorCode;
  @Int8()
  external int isDuplexSupported;
  @Int8()
  external int isColorSupported;
}

extension PrinterStatusDetailFfiExt on PrinterStatusDetailFfi {
  PrinterStatusDetail toDart() {
    return PrinterStatusDetail(
      printerId: printerId.toDartString(),
      isOnline: isOnline != 0,
      isReady: isReady != 0,
      hasPaperJam: hasPaperJam != 0,
      isOutOfPaper: isOutOfPaper != 0,
      isOutOfInk: isOutOfInk != 0,
      inkLevelBlack: inkLevelBlack,
      inkLevelCyan: inkLevelCyan,
      inkLevelMagenta: inkLevelMagenta,
      inkLevelYellow: inkLevelYellow,
      tonerLevel: tonerLevel,
      paperLevel: paperLevel,
      jobsInQueue: jobsInQueue,
      isWarmingUp: isWarmingUp != 0,
      printerState: printerState.toDartString(),
      stateReasons: stateReasons.toDartString(),
      statusMessage: statusMessage.toDartString(),
      errorCode: errorCode.toDartString(),
      isDuplexSupported: isDuplexSupported != 0,
      isColorSupported: isColorSupported != 0,
    );
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {
    if (printerId != nullptr) {
      malloc.free(printerId);
    }
    if (printerState != nullptr) {
      malloc.free(printerState);
    }
    if (stateReasons != nullptr) {
      malloc.free(stateReasons);
    }
    if (statusMessage != nullptr) {
      malloc.free(statusMessage);
    }
    if (errorCode != nullptr) {
      malloc.free(errorCode);
    }
  }
}

extension PrinterStatusDetailExt on PrinterStatusDetail {
  Pointer<PrinterStatusDetailFfi> toNative(Arena arena) {
    final ptr = arena<PrinterStatusDetailFfi>();
    ptr.ref.printerId = printerId.toNativeUtf8(allocator: arena);
    ptr.ref.isOnline = isOnline ? 1 : 0;
    ptr.ref.isReady = isReady ? 1 : 0;
    ptr.ref.hasPaperJam = hasPaperJam ? 1 : 0;
    ptr.ref.isOutOfPaper = isOutOfPaper ? 1 : 0;
    ptr.ref.isOutOfInk = isOutOfInk ? 1 : 0;
    ptr.ref.inkLevelBlack = inkLevelBlack;
    ptr.ref.inkLevelCyan = inkLevelCyan;
    ptr.ref.inkLevelMagenta = inkLevelMagenta;
    ptr.ref.inkLevelYellow = inkLevelYellow;
    ptr.ref.tonerLevel = tonerLevel;
    ptr.ref.paperLevel = paperLevel;
    ptr.ref.jobsInQueue = jobsInQueue;
    ptr.ref.isWarmingUp = isWarmingUp ? 1 : 0;
    ptr.ref.printerState = printerState.toNativeUtf8(allocator: arena);
    ptr.ref.stateReasons = stateReasons.toNativeUtf8(allocator: arena);
    ptr.ref.statusMessage = statusMessage.toNativeUtf8(allocator: arena);
    ptr.ref.errorCode = errorCode.toNativeUtf8(allocator: arena);
    ptr.ref.isDuplexSupported = isDuplexSupported ? 1 : 0;
    ptr.ref.isColorSupported = isColorSupported ? 1 : 0;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [PrinterInfo].
/// Extends [PrinterInfo] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrinterInfoProxy <: PrinterInfo`, a `Stream<PrinterInfoProxy>`
/// satisfies `Stream<PrinterInfo>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrinterInfo'.
final class PrinterInfoProxy extends PrinterInfo implements Finalizable {
  final Pointer<PrinterInfoFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrinterInfo',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrinterInfoProxy(this._native)
    : super(
        id: '',
        name: '',
        address: '',
        isDefault: false,
        isAvailable: false,
      ) {
    assert(
      _finalizer != null,
      'PrinterInfoProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get id => _native.ref.id.toDartString();
  @override
  String get name => _native.ref.name.toDartString();
  @override
  String get address => _native.ref.address.toDartString();
  @override
  bool get isDefault => _native.ref.isDefault != 0;
  @override
  bool get isAvailable => _native.ref.isAvailable != 0;

  /// Eagerly copies all fields to a plain [PrinterInfo] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrinterInfo toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrinterCapabilities].
/// Extends [PrinterCapabilities] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrinterCapabilitiesProxy <: PrinterCapabilities`, a `Stream<PrinterCapabilitiesProxy>`
/// satisfies `Stream<PrinterCapabilities>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrinterCapabilities'.
final class PrinterCapabilitiesProxy extends PrinterCapabilities
    implements Finalizable {
  final Pointer<PrinterCapabilitiesFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrinterCapabilities',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrinterCapabilitiesProxy(this._native)
    : super(
        supportsColor: false,
        supportsDuplex: false,
        supportsCopy: false,
        maxCopies: 0,
        minMarginTop: 0.0,
        minMarginBottom: 0.0,
        minMarginLeft: 0.0,
        minMarginRight: 0.0,
        supportsA4: false,
        supportsA5: false,
        supportsLetter: false,
        supportsLegal: false,
        supportsDraftQuality: false,
        supportsNormalQuality: false,
        supportsHighQuality: false,
        supportsBestQuality: false,
        maxResolutionDpi: 0,
        supportsCustomPaper: false,
        supportsBorderless: false,
        inputTrays: '',
      ) {
    assert(
      _finalizer != null,
      'PrinterCapabilitiesProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  bool get supportsColor => _native.ref.supportsColor != 0;
  @override
  bool get supportsDuplex => _native.ref.supportsDuplex != 0;
  @override
  bool get supportsCopy => _native.ref.supportsCopy != 0;
  @override
  int get maxCopies => _native.ref.maxCopies;
  @override
  double get minMarginTop => _native.ref.minMarginTop;
  @override
  double get minMarginBottom => _native.ref.minMarginBottom;
  @override
  double get minMarginLeft => _native.ref.minMarginLeft;
  @override
  double get minMarginRight => _native.ref.minMarginRight;
  @override
  bool get supportsA4 => _native.ref.supportsA4 != 0;
  @override
  bool get supportsA5 => _native.ref.supportsA5 != 0;
  @override
  bool get supportsLetter => _native.ref.supportsLetter != 0;
  @override
  bool get supportsLegal => _native.ref.supportsLegal != 0;
  @override
  bool get supportsDraftQuality => _native.ref.supportsDraftQuality != 0;
  @override
  bool get supportsNormalQuality => _native.ref.supportsNormalQuality != 0;
  @override
  bool get supportsHighQuality => _native.ref.supportsHighQuality != 0;
  @override
  bool get supportsBestQuality => _native.ref.supportsBestQuality != 0;
  @override
  int get maxResolutionDpi => _native.ref.maxResolutionDpi;
  @override
  bool get supportsCustomPaper => _native.ref.supportsCustomPaper != 0;
  @override
  bool get supportsBorderless => _native.ref.supportsBorderless != 0;
  @override
  String get inputTrays => _native.ref.inputTrays.toDartString();

  /// Eagerly copies all fields to a plain [PrinterCapabilities] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrinterCapabilities toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrintSettings].
/// Extends [PrintSettings] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintSettingsProxy <: PrintSettings`, a `Stream<PrintSettingsProxy>`
/// satisfies `Stream<PrintSettings>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintSettings'.
final class PrintSettingsProxy extends PrintSettings implements Finalizable {
  final Pointer<PrintSettingsFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintSettings',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrintSettingsProxy(this._native)
    : super(
        printerId: '',
        paperSize: PaperSize.values.first,
        orientationDegrees: 0.0,
        quality: PrintQuality.values.first,
        copies: 0,
        collate: false,
        duplex: false,
        color: false,
        marginTop: 0.0,
        marginBottom: 0.0,
        marginLeft: 0.0,
        marginRight: 0.0,
        jobName: '',
        pagesPerSheet: 0,
        showPrintDialog: false,
        pageRangeFrom: 0,
        pageRangeTo: 0,
        customPaperWidth: 0.0,
        customPaperHeight: 0.0,
        fitToPage: false,
        mediaType: MediaType.values.first,
        headerText: '',
        footerText: '',
        inputTray: '',
        networkTimeoutSeconds: 0,
      ) {
    assert(
      _finalizer != null,
      'PrintSettingsProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get printerId => _native.ref.printerId.toDartString();
  @override
  PaperSize get paperSize => _native.ref.paperSize.toPaperSize();
  @override
  double get orientationDegrees => _native.ref.orientationDegrees;
  @override
  PrintQuality get quality => _native.ref.quality.toPrintQuality();
  @override
  int get copies => _native.ref.copies;
  @override
  bool get collate => _native.ref.collate != 0;
  @override
  bool get duplex => _native.ref.duplex != 0;
  @override
  bool get color => _native.ref.color != 0;
  @override
  double get marginTop => _native.ref.marginTop;
  @override
  double get marginBottom => _native.ref.marginBottom;
  @override
  double get marginLeft => _native.ref.marginLeft;
  @override
  double get marginRight => _native.ref.marginRight;
  @override
  String get jobName => _native.ref.jobName.toDartString();
  @override
  int get pagesPerSheet => _native.ref.pagesPerSheet;
  @override
  bool get showPrintDialog => _native.ref.showPrintDialog != 0;
  @override
  int get pageRangeFrom => _native.ref.pageRangeFrom;
  @override
  int get pageRangeTo => _native.ref.pageRangeTo;
  @override
  double get customPaperWidth => _native.ref.customPaperWidth;
  @override
  double get customPaperHeight => _native.ref.customPaperHeight;
  @override
  bool get fitToPage => _native.ref.fitToPage != 0;
  @override
  MediaType get mediaType => _native.ref.mediaType.toMediaType();
  @override
  String get headerText => _native.ref.headerText.toDartString();
  @override
  String get footerText => _native.ref.footerText.toDartString();
  @override
  String get inputTray => _native.ref.inputTray.toDartString();
  @override
  int get networkTimeoutSeconds => _native.ref.networkTimeoutSeconds;

  /// Eagerly copies all fields to a plain [PrintSettings] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintSettings toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrintDocument].
/// Extends [PrintDocument] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintDocumentProxy <: PrintDocument`, a `Stream<PrintDocumentProxy>`
/// satisfies `Stream<PrintDocument>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintDocument'.
final class PrintDocumentProxy extends PrintDocument implements Finalizable {
  final Pointer<PrintDocumentFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintDocument',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrintDocumentProxy(this._native)
    : super(
        id: '',
        title: '',
        type: DocumentType.values.first,
        data: Uint8List(0),
      ) {
    assert(
      _finalizer != null,
      'PrintDocumentProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get id => _native.ref.id.toDartString();
  @override
  String get title => _native.ref.title.toDartString();
  @override
  DocumentType get type => _native.ref.type.toDocumentType();
  @override
  Uint8List get data => _native.ref.data.asTypedList(_native.ref.dataLength);

  /// Eagerly copies all fields to a plain [PrintDocument] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintDocument toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrintJob].
/// Extends [PrintJob] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintJobProxy <: PrintJob`, a `Stream<PrintJobProxy>`
/// satisfies `Stream<PrintJob>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintJob'.
final class PrintJobProxy extends PrintJob implements Finalizable {
  final Pointer<PrintJobFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintJob',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrintJobProxy(this._native)
    : super(
        id: '',
        printerId: '',
        documentTitle: '',
        state: PrintState.values.first,
        progress: 0,
        createdAtMillis: 0,
        completedAtMillis: 0,
        errorMessage: '',
        pagesPrinted: 0,
      ) {
    assert(
      _finalizer != null,
      'PrintJobProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get id => _native.ref.id.toDartString();
  @override
  String get printerId => _native.ref.printerId.toDartString();
  @override
  String get documentTitle => _native.ref.documentTitle.toDartString();
  @override
  PrintState get state => _native.ref.state.toPrintState();
  @override
  int get progress => _native.ref.progress;
  @override
  int get createdAtMillis => _native.ref.createdAtMillis;
  @override
  int get completedAtMillis => _native.ref.completedAtMillis;
  @override
  String get errorMessage => _native.ref.errorMessage.toDartString();
  @override
  int get pagesPrinted => _native.ref.pagesPrinted;

  /// Eagerly copies all fields to a plain [PrintJob] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintJob toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrintResult].
/// Extends [PrintResult] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintResultProxy <: PrintResult`, a `Stream<PrintResultProxy>`
/// satisfies `Stream<PrintResult>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintResult'.
final class PrintResultProxy extends PrintResult implements Finalizable {
  final Pointer<PrintResultFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintResult',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrintResultProxy(this._native)
    : super(success: false, jobId: '', errorMessage: '', errorCode: '') {
    assert(
      _finalizer != null,
      'PrintResultProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  bool get success => _native.ref.success != 0;
  @override
  String get jobId => _native.ref.jobId.toDartString();
  @override
  String get errorMessage => _native.ref.errorMessage.toDartString();
  @override
  String get errorCode => _native.ref.errorCode.toDartString();

  /// Eagerly copies all fields to a plain [PrintResult] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintResult toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrintJobUpdate].
/// Extends [PrintJobUpdate] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrintJobUpdateProxy <: PrintJobUpdate`, a `Stream<PrintJobUpdateProxy>`
/// satisfies `Stream<PrintJobUpdate>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrintJobUpdate'.
final class PrintJobUpdateProxy extends PrintJobUpdate implements Finalizable {
  final Pointer<PrintJobUpdateFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrintJobUpdate',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrintJobUpdateProxy(this._native)
    : super(
        jobId: '',
        state: PrintState.values.first,
        progress: 0,
        message: '',
      ) {
    assert(
      _finalizer != null,
      'PrintJobUpdateProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get jobId => _native.ref.jobId.toDartString();
  @override
  PrintState get state => _native.ref.state.toPrintState();
  @override
  int get progress => _native.ref.progress;
  @override
  String get message => _native.ref.message.toDartString();

  /// Eagerly copies all fields to a plain [PrintJobUpdate] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrintJobUpdate toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrinterStatus].
/// Extends [PrinterStatus] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrinterStatusProxy <: PrinterStatus`, a `Stream<PrinterStatusProxy>`
/// satisfies `Stream<PrinterStatus>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrinterStatus'.
final class PrinterStatusProxy extends PrinterStatus implements Finalizable {
  final Pointer<PrinterStatusFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrinterStatus',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrinterStatusProxy(this._native)
    : super(
        printerId: '',
        isOnline: false,
        isPrinting: false,
        jobsInQueue: 0,
        statusMessage: '',
        inkLevel: 0,
        tonerLevel: 0,
        paperLevel: 0,
        errorCode: '',
        isWarmingUp: false,
      ) {
    assert(
      _finalizer != null,
      'PrinterStatusProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get printerId => _native.ref.printerId.toDartString();
  @override
  bool get isOnline => _native.ref.isOnline != 0;
  @override
  bool get isPrinting => _native.ref.isPrinting != 0;
  @override
  int get jobsInQueue => _native.ref.jobsInQueue;
  @override
  String get statusMessage => _native.ref.statusMessage.toDartString();
  @override
  int get inkLevel => _native.ref.inkLevel;
  @override
  int get tonerLevel => _native.ref.tonerLevel;
  @override
  int get paperLevel => _native.ref.paperLevel;
  @override
  String get errorCode => _native.ref.errorCode.toDartString();
  @override
  bool get isWarmingUp => _native.ref.isWarmingUp != 0;

  /// Eagerly copies all fields to a plain [PrinterStatus] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrinterStatus toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PreviewResult].
/// Extends [PreviewResult] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PreviewResultProxy <: PreviewResult`, a `Stream<PreviewResultProxy>`
/// satisfies `Stream<PreviewResult>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PreviewResult'.
final class PreviewResultProxy extends PreviewResult implements Finalizable {
  final Pointer<PreviewResultFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PreviewResult',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PreviewResultProxy(this._native) : super(bytes: Uint8List(0), length: 0) {
    assert(
      _finalizer != null,
      'PreviewResultProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  Uint8List get bytes => _native.ref.bytes.asTypedList(_native.ref.length);
  @override
  int get length => _native.ref.length;

  /// Eagerly copies all fields to a plain [PreviewResult] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PreviewResult toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [DiscoveredPrinter].
/// Extends [DiscoveredPrinter] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `DiscoveredPrinterProxy <: DiscoveredPrinter`, a `Stream<DiscoveredPrinterProxy>`
/// satisfies `Stream<DiscoveredPrinter>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_DiscoveredPrinter'.
final class DiscoveredPrinterProxy extends DiscoveredPrinter
    implements Finalizable {
  final Pointer<DiscoveredPrinterFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_DiscoveredPrinter',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  DiscoveredPrinterProxy(this._native)
    : super(
        id: '',
        name: '',
        host: '',
        port: 0,
        serviceType: '',
        uri: '',
        isAvailable: false,
      ) {
    assert(
      _finalizer != null,
      'DiscoveredPrinterProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get id => _native.ref.id.toDartString();
  @override
  String get name => _native.ref.name.toDartString();
  @override
  String get host => _native.ref.host.toDartString();
  @override
  int get port => _native.ref.port;
  @override
  String get serviceType => _native.ref.serviceType.toDartString();
  @override
  String get uri => _native.ref.uri.toDartString();
  @override
  bool get isAvailable => _native.ref.isAvailable != 0;

  /// Eagerly copies all fields to a plain [DiscoveredPrinter] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  DiscoveredPrinter toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

/// Zero-copy proxy for [PrinterStatusDetail].
/// Extends [PrinterStatusDetail] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `PrinterStatusDetailProxy <: PrinterStatusDetail`, a `Stream<PrinterStatusDetailProxy>`
/// satisfies `Stream<PrinterStatusDetail>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_printing_release_PrinterStatusDetail'.
final class PrinterStatusDetailProxy extends PrinterStatusDetail
    implements Finalizable {
  final Pointer<PrinterStatusDetailFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_printing_release_PrinterStatusDetail',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] after passing the pointer here.
  PrinterStatusDetailProxy(this._native)
    : super(
        printerId: '',
        isOnline: false,
        isReady: false,
        hasPaperJam: false,
        isOutOfPaper: false,
        isOutOfInk: false,
        inkLevelBlack: 0,
        inkLevelCyan: 0,
        inkLevelMagenta: 0,
        inkLevelYellow: 0,
        tonerLevel: 0,
        paperLevel: 0,
        jobsInQueue: 0,
        isWarmingUp: false,
        printerState: '',
        stateReasons: '',
        statusMessage: '',
        errorCode: '',
        isDuplexSupported: false,
        isColorSupported: false,
      ) {
    assert(
      _finalizer != null,
      'PrinterStatusDetailProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  String get printerId => _native.ref.printerId.toDartString();
  @override
  bool get isOnline => _native.ref.isOnline != 0;
  @override
  bool get isReady => _native.ref.isReady != 0;
  @override
  bool get hasPaperJam => _native.ref.hasPaperJam != 0;
  @override
  bool get isOutOfPaper => _native.ref.isOutOfPaper != 0;
  @override
  bool get isOutOfInk => _native.ref.isOutOfInk != 0;
  @override
  int get inkLevelBlack => _native.ref.inkLevelBlack;
  @override
  int get inkLevelCyan => _native.ref.inkLevelCyan;
  @override
  int get inkLevelMagenta => _native.ref.inkLevelMagenta;
  @override
  int get inkLevelYellow => _native.ref.inkLevelYellow;
  @override
  int get tonerLevel => _native.ref.tonerLevel;
  @override
  int get paperLevel => _native.ref.paperLevel;
  @override
  int get jobsInQueue => _native.ref.jobsInQueue;
  @override
  bool get isWarmingUp => _native.ref.isWarmingUp != 0;
  @override
  String get printerState => _native.ref.printerState.toDartString();
  @override
  String get stateReasons => _native.ref.stateReasons.toDartString();
  @override
  String get statusMessage => _native.ref.statusMessage.toDartString();
  @override
  String get errorCode => _native.ref.errorCode.toDartString();
  @override
  bool get isDuplexSupported => _native.ref.isDuplexSupported != 0;
  @override
  bool get isColorSupported => _native.ref.isColorSupported != 0;

  /// Eagerly copies all fields to a plain [PrinterStatusDetail] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  PrinterStatusDetail toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension PrinterInfoRecordExt on PrinterInfo {
  static PrinterInfo fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static PrinterInfo fromReader(RecordReader r) => PrinterInfo(
    id: r.readString(),
    name: r.readString(),
    address: r.readString(),
    isDefault: r.readBool(),
    isAvailable: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(id);
    writer.writeString(name);
    writer.writeString(address);
    writer.writeBool(isDefault);
    writer.writeBool(isAvailable);
  }
}

class _NitroPrintingImpl extends NitroPrinting {
  final DynamicLibrary _dylib;

  _NitroPrintingImpl() : _dylib = NitroRuntime.loadLib('nitro_printing') {
    final initSw = Stopwatch()..start();
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_printing_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_printing: Dart API DL initialization failed with code $initCode.',
      );
    }
    PrinterInfoProxy._init(_dylib);
    PrinterCapabilitiesProxy._init(_dylib);
    PrintSettingsProxy._init(_dylib);
    PrintDocumentProxy._init(_dylib);
    PrintJobProxy._init(_dylib);
    PrintResultProxy._init(_dylib);
    PrintJobUpdateProxy._init(_dylib);
    PrinterStatusProxy._init(_dylib);
    PreviewResultProxy._init(_dylib);
    DiscoveredPrinterProxy._init(_dylib);
    PrinterStatusDetailProxy._init(_dylib);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_printing)',
      'initialized in ${initSw.elapsedMicroseconds} µs',
    );
  }

  late final int Function() _isPrintingSupportedPtr = _dylib
      .lookup<NativeFunction<Int8 Function()>>(
        'nitro_printing_is_printing_supported',
      )
      .asFunction<int Function()>(isLeaf: true);
  late final int Function() _getPrintersCountPtr = _dylib
      .lookup<NativeFunction<Int64 Function()>>(
        'nitro_printing_get_printers_count',
      )
      .asFunction<int Function()>(isLeaf: true);
  late final Pointer<Uint8> Function() _getAllPrintersPtr = _dylib
      .lookupFunction<Pointer<Uint8> Function(), Pointer<Uint8> Function()>(
        'nitro_printing_get_all_printers',
      );
  late final Pointer<Void> Function(int) _getPrinterAtPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Int64),
        Pointer<Void> Function(int)
      >('nitro_printing_get_printer_at');
  late final Pointer<Void> Function() _getDefaultPrinterPtr = _dylib
      .lookupFunction<Pointer<Void> Function(), Pointer<Void> Function()>(
        'nitro_printing_get_default_printer',
      );
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getPrinterDriverVersionPtr =
      _dylib.lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>),
        Pointer<Utf8> Function(Pointer<Utf8>)
      >('nitro_printing_get_printer_driver_version');
  late final Pointer<Void> Function(Pointer<Utf8>) _getPrinterCapabilitiesPtr =
      _dylib.lookupFunction<
        Pointer<Void> Function(Pointer<Utf8>),
        Pointer<Void> Function(Pointer<Utf8>)
      >('nitro_printing_get_printer_capabilities');
  late final Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>)
  _printTextPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>),
        Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>)
      >('nitro_printing_print_text');
  late final Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
  _printImagePtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Uint8>, Int64, Pointer<Void>),
        Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
      >('nitro_printing_print_image');
  late final Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
  _printPdfPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Uint8>, Int64, Pointer<Void>),
        Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
      >('nitro_printing_print_pdf');
  late final Pointer<Void> Function(Pointer<Void>, Pointer<Void>)
  _printDocumentPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Void>, Pointer<Void>),
        Pointer<Void> Function(Pointer<Void>, Pointer<Void>)
      >('nitro_printing_print_document');
  late final int Function(Pointer<Utf8>, Pointer<Void>) _printFilePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>, Pointer<Void>),
        int Function(Pointer<Utf8>, Pointer<Void>)
      >('nitro_printing_print_file');
  late final Pointer<Void> Function(Pointer<Void>, Pointer<Void>)
  _renderPreviewPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Void>, Pointer<Void>),
        Pointer<Void> Function(Pointer<Void>, Pointer<Void>)
      >('nitro_printing_render_preview');
  late final int Function(Pointer<Void>) _getPageCountPtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Void>),
        int Function(Pointer<Void>)
      >('nitro_printing_get_page_count');
  late final int Function(Pointer<Void>, Pointer<Utf8>, Pointer<Void>)
  _printToFilePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Void>, Pointer<Utf8>, Pointer<Void>),
        int Function(Pointer<Void>, Pointer<Utf8>, Pointer<Void>)
      >('nitro_printing_print_to_file');
  late final int Function(Pointer<Utf8>) _cancelPrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_cancel_print_job');
  late final int Function(Pointer<Utf8>) _pausePrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_pause_print_job');
  late final int Function(Pointer<Utf8>) _resumePrintJobPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_resume_print_job');
  late final int Function() _clearPrintQueuePtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_clear_print_queue',
      );
  late final int Function() _getPrintJobsCountPtr = _dylib
      .lookupFunction<Int64 Function(), int Function()>(
        'nitro_printing_get_print_jobs_count',
      );
  late final Pointer<Void> Function(int) _getPrintJobAtPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Int64),
        Pointer<Void> Function(int)
      >('nitro_printing_get_print_job_at');
  late final Pointer<Void> Function(Pointer<Utf8>) _getPrintJobStatusPtr =
      _dylib.lookupFunction<
        Pointer<Void> Function(Pointer<Utf8>),
        Pointer<Void> Function(Pointer<Utf8>)
      >('nitro_printing_get_print_job_status');
  late final int Function() _startPrinterDiscoveryPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_start_printer_discovery',
      );
  late final int Function() _stopPrinterDiscoveryPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_stop_printer_discovery',
      );
  late final int Function(Pointer<Utf8>, int) _testPrinterConnectionPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>, Int64),
        int Function(Pointer<Utf8>, int)
      >('nitro_printing_test_printer_connection');
  late final int Function(Pointer<Utf8>) _setDefaultPrinterPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_set_default_printer');
  late final int Function(Pointer<Utf8>) _openSystemPrintQueuePtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_open_system_print_queue');
  late final int Function(Pointer<Utf8>) _openPrinterPropertiesPtr = _dylib
      .lookupFunction<
        Int8 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_printing_open_printer_properties');
  late final Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
  _printRawPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Uint8>, Int64, Pointer<Void>),
        Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
      >('nitro_printing_print_raw');
  late final Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
  _printEscPosPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Uint8>, Int64, Pointer<Void>),
        Pointer<Void> Function(Pointer<Uint8>, int, Pointer<Void>)
      >('nitro_printing_print_esc_pos');
  late final Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>) _printZplPtr =
      _dylib.lookupFunction<
        Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>),
        Pointer<Void> Function(Pointer<Utf8>, Pointer<Void>)
      >('nitro_printing_print_zpl');
  late final int Function() _cancelRawPrintPtr = _dylib
      .lookupFunction<Int8 Function(), int Function()>(
        'nitro_printing_cancel_raw_print',
      );
  late final Pointer<Void> Function(Pointer<Utf8>, int)
  _getPrinterStatusDetailPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Utf8>, Int64),
        Pointer<Void> Function(Pointer<Utf8>, int)
      >('nitro_printing_get_printer_status_detail');
  late final void Function(int) _registerOnPrintJobChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_print_job_changed_stream',
      );
  late final void Function(int) _releaseOnPrintJobChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_print_job_changed_stream',
      );
  late final void Function(int) _registerOnPrinterStatusChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_printer_status_changed_stream',
      );
  late final void Function(int) _releaseOnPrinterStatusChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_printer_status_changed_stream',
      );
  late final void Function(int) _registerOnPrinterDiscoveredPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_register_on_printer_discovered_stream',
      );
  late final void Function(int) _releaseOnPrinterDiscoveredPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_printing_release_on_printer_discovered_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_printing_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_printing_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_printing_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_printing_clear_error');

  @override
  void dispose() {
    NitroRuntime.logLifecycle('dispose(nitro_printing)', 'disposing');
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_printing)', 'disposed');
  }

  @override
  bool isPrintingSupported() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _isPrintingSupportedPtr();
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return res != 0;
    }, methodName: 'isPrintingSupported');
  }

  @override
  int getPrintersCount() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getPrintersCountPtr();
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return res;
    }, methodName: 'getPrintersCount');
  }

  @override
  List<PrinterInfo> getAllPrinters() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getAllPrintersPtr();
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return LazyRecordList.decode(
        res,
        (r) => PrinterInfoRecordExt.fromReader(r),
      );
    }, methodName: 'getAllPrinters');
  }

  @override
  PrinterInfo getPrinterAt(int index) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getPrinterAtPtr(index);
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      if (res == nullptr) {
        throw StateError('getPrinterAt returned null');
      }
      final structPtr = Pointer<PrinterInfoFfi>.fromAddress(res.address);
      final PrinterInfo decoded;
      try {
        decoded = structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
      return decoded;
    }, methodName: 'getPrinterAt');
  }

  @override
  PrinterInfo getDefaultPrinter() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getDefaultPrinterPtr();
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      if (res == nullptr) {
        throw StateError('getDefaultPrinter returned null');
      }
      final structPtr = Pointer<PrinterInfoFfi>.fromAddress(res.address);
      final PrinterInfo decoded;
      try {
        decoded = structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
      return decoded;
    }, methodName: 'getDefaultPrinter');
  }

  @override
  String getPrinterDriverVersion(String printerId) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _getPrinterDriverVersionPtr(
          printerId.toNativeUtf8(allocator: arena),
        );
        NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
        return res.toDartStringWithFree();
      }),
      methodName: 'getPrinterDriverVersion',
    );
  }

  @override
  PrinterCapabilities getPrinterCapabilities(String printerId) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _getPrinterCapabilitiesPtr(
          printerId.toNativeUtf8(allocator: arena),
        );
        NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
        if (res == nullptr) {
          throw StateError('getPrinterCapabilities returned null');
        }
        final structPtr = Pointer<PrinterCapabilitiesFfi>.fromAddress(
          res.address,
        );
        final PrinterCapabilities decoded;
        try {
          decoded = structPtr.ref.toDart();
        } finally {
          structPtr.ref.freeFields();
          malloc.free(structPtr);
        }
        return decoded;
      }),
      methodName: 'getPrinterCapabilities',
    );
  }

  @override
  Future<PrintResult> printText(String text, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printTextPtr,
        [
          text.toNativeUtf8(allocator: arena),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printText',
      );
      if (rawPtr == nullptr) {
        throw StateError('printText returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printImage(
    Uint8List imageData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printImagePtr,
        [
          imageData.toPointer(arena),
          imageData.length,
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printImage',
      );
      if (rawPtr == nullptr) {
        throw StateError('printImage returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printPdf(
    Uint8List pdfData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printPdfPtr,
        [
          pdfData.toPointer(arena),
          pdfData.length,
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printPdf',
      );
      if (rawPtr == nullptr) {
        throw StateError('printPdf returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printDocument(
    PrintDocument document, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printDocumentPtr,
        [
          document.toNative(arena).cast<Void>(),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printDocument',
      );
      if (rawPtr == nullptr) {
        throw StateError('printDocument returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> printFile(String filePath, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _printFilePtr,
        [
          filePath.toNativeUtf8(allocator: arena),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printFile',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PreviewResult> renderPreview(
    PrintDocument document, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _renderPreviewPtr,
        [
          document.toNative(arena).cast<Void>(),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'renderPreview',
      );
      if (rawPtr == nullptr) {
        throw StateError('renderPreview returned null');
      }
      final structPtr = Pointer<PreviewResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<int> getPageCount(PrintDocument document) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _getPageCountPtr,
        [document.toNative(arena).cast<Void>()],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPageCount',
      );
      return res;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> printToFile(
    PrintDocument document,
    String outputPath, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _printToFilePtr,
        [
          document.toNative(arena).cast<Void>(),
          outputPath.toNativeUtf8(allocator: arena),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printToFile',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> cancelPrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _cancelPrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'cancelPrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> pausePrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _pausePrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'pausePrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> resumePrintJob(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _resumePrintJobPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'resumePrintJob',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> clearPrintQueue() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _clearPrintQueuePtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'clearPrintQueue',
    );
    return res != 0;
  }

  @override
  Future<int> getPrintJobsCount() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _getPrintJobsCountPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getPrintJobsCount',
    );
    return res;
  }

  @override
  Future<PrintJob> getPrintJobAt(int index) async {
    checkDisposed();
    final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
      _getPrintJobAtPtr,
      [index],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'getPrintJobAt',
    );
    if (rawPtr == nullptr) {
      throw StateError('getPrintJobAt returned null');
    }
    final structPtr = Pointer<PrintJobFfi>.fromAddress(rawPtr.address);
    try {
      return structPtr.ref.toDart();
    } finally {
      structPtr.ref.freeFields();
      malloc.free(structPtr);
    }
  }

  @override
  Future<PrintJob> getPrintJobStatus(String jobId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _getPrintJobStatusPtr,
        [jobId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPrintJobStatus',
      );
      if (rawPtr == nullptr) {
        throw StateError('getPrintJobStatus returned null');
      }
      final structPtr = Pointer<PrintJobFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> startPrinterDiscovery() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _startPrinterDiscoveryPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'startPrinterDiscovery',
    );
    return res != 0;
  }

  @override
  Future<bool> stopPrinterDiscovery() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _stopPrinterDiscoveryPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'stopPrinterDiscovery',
    );
    return res != 0;
  }

  @override
  Future<bool> testPrinterConnection(
    String printerId, {
    int? timeoutSeconds,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _testPrinterConnectionPtr,
        [printerId.toNativeUtf8(allocator: arena), timeoutSeconds ?? -1],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'testPrinterConnection',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> setDefaultPrinter(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _setDefaultPrinterPtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'setDefaultPrinter',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> openSystemPrintQueue(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _openSystemPrintQueuePtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'openSystemPrintQueue',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> openPrinterProperties(String printerId) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<int>(
        _openPrinterPropertiesPtr,
        [printerId.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'openPrinterProperties',
      );
      return res != 0;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printRaw(
    Uint8List data, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printRawPtr,
        [
          data.toPointer(arena),
          data.length,
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printRaw',
      );
      if (rawPtr == nullptr) {
        throw StateError('printRaw returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printEscPos(
    Uint8List escPosData, {
    PrintSettings? settings,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printEscPosPtr,
        [
          escPosData.toPointer(arena),
          escPosData.length,
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printEscPos',
      );
      if (rawPtr == nullptr) {
        throw StateError('printEscPos returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<PrintResult> printZpl(String zpl, {PrintSettings? settings}) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _printZplPtr,
        [
          zpl.toNativeUtf8(allocator: arena),
          settings != null ? settings.toNative(arena).cast<Void>() : nullptr,
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'printZpl',
      );
      if (rawPtr == nullptr) {
        throw StateError('printZpl returned null');
      }
      final structPtr = Pointer<PrintResultFfi>.fromAddress(rawPtr.address);
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<bool> cancelRawPrint() async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _cancelRawPrintPtr,
      [],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'cancelRawPrint',
    );
    return res != 0;
  }

  @override
  Future<PrinterStatusDetail> getPrinterStatusDetail(
    String printerId, {
    int? timeoutSeconds,
  }) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _getPrinterStatusDetailPtr,
        [printerId.toNativeUtf8(allocator: arena), timeoutSeconds ?? -1],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getPrinterStatusDetail',
      );
      if (rawPtr == nullptr) {
        throw StateError('getPrinterStatusDetail returned null');
      }
      final structPtr = Pointer<PrinterStatusDetailFfi>.fromAddress(
        rawPtr.address,
      );
      try {
        return structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Stream<PrintJobUpdate> onPrintJobChanged() {
    checkDisposed();
    return NitroRuntime.openStream<PrintJobUpdateProxy>(
      register: (port) => _registerOnPrintJobChangedPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrintJobChanged',
          );
        }
        return PrintJobUpdateProxy(
          Pointer<PrintJobUpdateFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseOnPrintJobChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<PrinterStatus> onPrinterStatusChanged() {
    checkDisposed();
    return NitroRuntime.openStream<PrinterStatusProxy>(
      register: (port) => _registerOnPrinterStatusChangedPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrinterStatusChanged',
          );
        }
        return PrinterStatusProxy(
          Pointer<PrinterStatusFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseOnPrinterStatusChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<DiscoveredPrinter> onPrinterDiscovered() {
    checkDisposed();
    return NitroRuntime.openStream<DiscoveredPrinterProxy>(
      register: (port) => _registerOnPrinterDiscoveredPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onPrinterDiscovered',
          );
        }
        return DiscoveredPrinterProxy(
          Pointer<DiscoveredPrinterFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseOnPrinterDiscoveredPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
