// HybridNitroPrinting — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_printing.native.g.h"

#include <string>

class HybridNitroPrintingImpl final : public HybridNitroPrinting {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroPrinting
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_printing_register_impl(new HybridNitroPrintingImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
