// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.5
// Generated from: nitro_printing.native.dart
import Foundation
import Combine

public protocol NitroEncodable {
    func toNative() -> UnsafeMutablePointer<UInt8>?
}

// --- Enums ---
public enum PrintState: Int64 {
  case idle = 0
  case printing = 1
  case completed = 2
  case cancelled = 3
  case failed = 4
  case paused = 5
}

public enum PrintQuality: Int64 {
  case draft = 0
  case normal = 1
  case high = 2
  case best = 3
}

public enum PaperSize: Int64 {
  case a4 = 0
  case a5 = 1
  case letter = 2
  case legal = 3
  case custom = 4
}

public enum DocumentType: Int64 {
  case plainText = 0
  case html = 1
  case pdf = 2
  case image = 3
}

public enum MediaType: Int64 {
  case plain = 0
  case glossy = 1
  case matte = 2
  case photo = 3
  case label = 4
  case envelope = 5
}

// --- Structs ---
public struct PreviewResult {
  public var bytes: UnsafeMutablePointer<UInt8>?
  public var length: Int64
}

// C-ABI shadow — layout matches the C typedef PreviewResult
fileprivate struct _PreviewResultC {
  var bytes: UnsafeMutablePointer<UInt8>?
  var length: Int64

  static func fromSwift(_ s: PreviewResult) -> _PreviewResultC {
    return _PreviewResultC(
      bytes: s.bytes,
      length: s.length
    )
  }

  func toSwift() -> PreviewResult {
    return PreviewResult(
      bytes: bytes,
      length: length
    )
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

public struct PrinterInfo: NitroEncodable {
  public var id: String
  public var name: String
  public var address: String
  public var isDefault: Bool
  public var isAvailable: Bool

  public init(id: String, name: String, address: String, isDefault: Bool, isAvailable: Bool) {
    self.id = id
    self.name = name
    self.address = address
    self.isDefault = isDefault
    self.isAvailable = isAvailable
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrinterInfo {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrinterInfo {
    return PrinterInfo(
      id: r.readString(),
      name: r.readString(),
      address: r.readString(),
      isDefault: r.readBool(),
      isAvailable: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(id)
    writer.writeString(name)
    writer.writeString(address)
    writer.writeBool(isDefault)
    writer.writeBool(isAvailable)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrinterCapabilities: NitroEncodable {
  public var supportsColor: Bool
  public var supportsDuplex: Bool
  public var supportsCopy: Bool
  public var maxCopies: Int64
  public var minMarginTop: Double
  public var minMarginBottom: Double
  public var minMarginLeft: Double
  public var minMarginRight: Double
  public var supportsA4: Bool
  public var supportsA5: Bool
  public var supportsLetter: Bool
  public var supportsLegal: Bool
  public var supportsDraftQuality: Bool
  public var supportsNormalQuality: Bool
  public var supportsHighQuality: Bool
  public var supportsBestQuality: Bool
  public var maxResolutionDpi: Int64
  public var supportsCustomPaper: Bool
  public var supportsBorderless: Bool
  public var inputTrays: String

  public init(supportsColor: Bool, supportsDuplex: Bool, supportsCopy: Bool, maxCopies: Int64, minMarginTop: Double, minMarginBottom: Double, minMarginLeft: Double, minMarginRight: Double, supportsA4: Bool, supportsA5: Bool, supportsLetter: Bool, supportsLegal: Bool, supportsDraftQuality: Bool, supportsNormalQuality: Bool, supportsHighQuality: Bool, supportsBestQuality: Bool, maxResolutionDpi: Int64, supportsCustomPaper: Bool, supportsBorderless: Bool, inputTrays: String) {
    self.supportsColor = supportsColor
    self.supportsDuplex = supportsDuplex
    self.supportsCopy = supportsCopy
    self.maxCopies = maxCopies
    self.minMarginTop = minMarginTop
    self.minMarginBottom = minMarginBottom
    self.minMarginLeft = minMarginLeft
    self.minMarginRight = minMarginRight
    self.supportsA4 = supportsA4
    self.supportsA5 = supportsA5
    self.supportsLetter = supportsLetter
    self.supportsLegal = supportsLegal
    self.supportsDraftQuality = supportsDraftQuality
    self.supportsNormalQuality = supportsNormalQuality
    self.supportsHighQuality = supportsHighQuality
    self.supportsBestQuality = supportsBestQuality
    self.maxResolutionDpi = maxResolutionDpi
    self.supportsCustomPaper = supportsCustomPaper
    self.supportsBorderless = supportsBorderless
    self.inputTrays = inputTrays
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrinterCapabilities {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrinterCapabilities {
    return PrinterCapabilities(
      supportsColor: r.readBool(),
      supportsDuplex: r.readBool(),
      supportsCopy: r.readBool(),
      maxCopies: r.readInt(),
      minMarginTop: r.readDouble(),
      minMarginBottom: r.readDouble(),
      minMarginLeft: r.readDouble(),
      minMarginRight: r.readDouble(),
      supportsA4: r.readBool(),
      supportsA5: r.readBool(),
      supportsLetter: r.readBool(),
      supportsLegal: r.readBool(),
      supportsDraftQuality: r.readBool(),
      supportsNormalQuality: r.readBool(),
      supportsHighQuality: r.readBool(),
      supportsBestQuality: r.readBool(),
      maxResolutionDpi: r.readInt(),
      supportsCustomPaper: r.readBool(),
      supportsBorderless: r.readBool(),
      inputTrays: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(supportsColor)
    writer.writeBool(supportsDuplex)
    writer.writeBool(supportsCopy)
    writer.writeInt(maxCopies)
    writer.writeDouble(minMarginTop)
    writer.writeDouble(minMarginBottom)
    writer.writeDouble(minMarginLeft)
    writer.writeDouble(minMarginRight)
    writer.writeBool(supportsA4)
    writer.writeBool(supportsA5)
    writer.writeBool(supportsLetter)
    writer.writeBool(supportsLegal)
    writer.writeBool(supportsDraftQuality)
    writer.writeBool(supportsNormalQuality)
    writer.writeBool(supportsHighQuality)
    writer.writeBool(supportsBestQuality)
    writer.writeInt(maxResolutionDpi)
    writer.writeBool(supportsCustomPaper)
    writer.writeBool(supportsBorderless)
    writer.writeString(inputTrays)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrintSettings: NitroEncodable {
  public var printerId: String
  public var paperSize: PaperSize
  public var orientationDegrees: Double
  public var quality: PrintQuality
  public var copies: Int64
  public var collate: Bool
  public var duplex: Bool
  public var color: Bool
  public var marginTop: Double
  public var marginBottom: Double
  public var marginLeft: Double
  public var marginRight: Double
  public var jobName: String
  public var pagesPerSheet: Int64
  public var showPrintDialog: Bool
  public var pageRangeFrom: Int64
  public var pageRangeTo: Int64
  public var customPaperWidth: Double
  public var customPaperHeight: Double
  public var fitToPage: Bool
  public var mediaType: MediaType
  public var headerText: String
  public var footerText: String
  public var inputTray: String
  public var networkTimeoutSeconds: Int64

  public init(printerId: String, paperSize: PaperSize, orientationDegrees: Double, quality: PrintQuality, copies: Int64, collate: Bool, duplex: Bool, color: Bool, marginTop: Double, marginBottom: Double, marginLeft: Double, marginRight: Double, jobName: String, pagesPerSheet: Int64, showPrintDialog: Bool, pageRangeFrom: Int64, pageRangeTo: Int64, customPaperWidth: Double, customPaperHeight: Double, fitToPage: Bool, mediaType: MediaType, headerText: String, footerText: String, inputTray: String, networkTimeoutSeconds: Int64) {
    self.printerId = printerId
    self.paperSize = paperSize
    self.orientationDegrees = orientationDegrees
    self.quality = quality
    self.copies = copies
    self.collate = collate
    self.duplex = duplex
    self.color = color
    self.marginTop = marginTop
    self.marginBottom = marginBottom
    self.marginLeft = marginLeft
    self.marginRight = marginRight
    self.jobName = jobName
    self.pagesPerSheet = pagesPerSheet
    self.showPrintDialog = showPrintDialog
    self.pageRangeFrom = pageRangeFrom
    self.pageRangeTo = pageRangeTo
    self.customPaperWidth = customPaperWidth
    self.customPaperHeight = customPaperHeight
    self.fitToPage = fitToPage
    self.mediaType = mediaType
    self.headerText = headerText
    self.footerText = footerText
    self.inputTray = inputTray
    self.networkTimeoutSeconds = networkTimeoutSeconds
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrintSettings {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrintSettings {
    return PrintSettings(
      printerId: r.readString(),
      paperSize: PaperSize(rawValue: r.readInt())!,
      orientationDegrees: r.readDouble(),
      quality: PrintQuality(rawValue: r.readInt())!,
      copies: r.readInt(),
      collate: r.readBool(),
      duplex: r.readBool(),
      color: r.readBool(),
      marginTop: r.readDouble(),
      marginBottom: r.readDouble(),
      marginLeft: r.readDouble(),
      marginRight: r.readDouble(),
      jobName: r.readString(),
      pagesPerSheet: r.readInt(),
      showPrintDialog: r.readBool(),
      pageRangeFrom: r.readInt(),
      pageRangeTo: r.readInt(),
      customPaperWidth: r.readDouble(),
      customPaperHeight: r.readDouble(),
      fitToPage: r.readBool(),
      mediaType: MediaType(rawValue: r.readInt())!,
      headerText: r.readString(),
      footerText: r.readString(),
      inputTray: r.readString(),
      networkTimeoutSeconds: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(printerId)
    writer.writeInt(paperSize.rawValue)
    writer.writeDouble(orientationDegrees)
    writer.writeInt(quality.rawValue)
    writer.writeInt(copies)
    writer.writeBool(collate)
    writer.writeBool(duplex)
    writer.writeBool(color)
    writer.writeDouble(marginTop)
    writer.writeDouble(marginBottom)
    writer.writeDouble(marginLeft)
    writer.writeDouble(marginRight)
    writer.writeString(jobName)
    writer.writeInt(pagesPerSheet)
    writer.writeBool(showPrintDialog)
    writer.writeInt(pageRangeFrom)
    writer.writeInt(pageRangeTo)
    writer.writeDouble(customPaperWidth)
    writer.writeDouble(customPaperHeight)
    writer.writeBool(fitToPage)
    writer.writeInt(mediaType.rawValue)
    writer.writeString(headerText)
    writer.writeString(footerText)
    writer.writeString(inputTray)
    writer.writeInt(networkTimeoutSeconds)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrintDocument: NitroEncodable {
  public var id: String
  public var title: String
  public var type: DocumentType
  public var data: Data

  public init(id: String, title: String, type: DocumentType, data: Data) {
    self.id = id
    self.title = title
    self.type = type
    self.data = data
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrintDocument {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrintDocument {
    return PrintDocument(
      id: r.readString(),
      title: r.readString(),
      type: DocumentType(rawValue: r.readInt())!,
      data: r.readBlob(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(id)
    writer.writeString(title)
    writer.writeInt(type.rawValue)
    writer.writeBlob(data)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrintJob: NitroEncodable {
  public var id: String
  public var printerId: String
  public var documentTitle: String
  public var state: PrintState
  public var progress: Int64
  public var createdAtMillis: Int64
  public var completedAtMillis: Int64
  public var errorMessage: String
  public var pagesPrinted: Int64

  public init(id: String, printerId: String, documentTitle: String, state: PrintState, progress: Int64, createdAtMillis: Int64, completedAtMillis: Int64, errorMessage: String, pagesPrinted: Int64) {
    self.id = id
    self.printerId = printerId
    self.documentTitle = documentTitle
    self.state = state
    self.progress = progress
    self.createdAtMillis = createdAtMillis
    self.completedAtMillis = completedAtMillis
    self.errorMessage = errorMessage
    self.pagesPrinted = pagesPrinted
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrintJob {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrintJob {
    return PrintJob(
      id: r.readString(),
      printerId: r.readString(),
      documentTitle: r.readString(),
      state: PrintState(rawValue: r.readInt())!,
      progress: r.readInt(),
      createdAtMillis: r.readInt(),
      completedAtMillis: r.readInt(),
      errorMessage: r.readString(),
      pagesPrinted: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(id)
    writer.writeString(printerId)
    writer.writeString(documentTitle)
    writer.writeInt(state.rawValue)
    writer.writeInt(progress)
    writer.writeInt(createdAtMillis)
    writer.writeInt(completedAtMillis)
    writer.writeString(errorMessage)
    writer.writeInt(pagesPrinted)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrintResult: NitroEncodable {
  public var success: Bool
  public var jobId: String
  public var errorMessage: String
  public var errorCode: String

  public init(success: Bool, jobId: String, errorMessage: String, errorCode: String) {
    self.success = success
    self.jobId = jobId
    self.errorMessage = errorMessage
    self.errorCode = errorCode
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrintResult {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrintResult {
    return PrintResult(
      success: r.readBool(),
      jobId: r.readString(),
      errorMessage: r.readString(),
      errorCode: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(success)
    writer.writeString(jobId)
    writer.writeString(errorMessage)
    writer.writeString(errorCode)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrintJobUpdate: NitroEncodable {
  public var jobId: String
  public var state: PrintState
  public var progress: Int64
  public var message: String

  public init(jobId: String, state: PrintState, progress: Int64, message: String) {
    self.jobId = jobId
    self.state = state
    self.progress = progress
    self.message = message
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrintJobUpdate {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrintJobUpdate {
    return PrintJobUpdate(
      jobId: r.readString(),
      state: PrintState(rawValue: r.readInt())!,
      progress: r.readInt(),
      message: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(jobId)
    writer.writeInt(state.rawValue)
    writer.writeInt(progress)
    writer.writeString(message)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrinterStatus: NitroEncodable {
  public var printerId: String
  public var isOnline: Bool
  public var isPrinting: Bool
  public var jobsInQueue: Int64
  public var statusMessage: String
  public var inkLevel: Int64
  public var tonerLevel: Int64
  public var paperLevel: Int64
  public var errorCode: String
  public var isWarmingUp: Bool

  public init(printerId: String, isOnline: Bool, isPrinting: Bool, jobsInQueue: Int64, statusMessage: String, inkLevel: Int64, tonerLevel: Int64, paperLevel: Int64, errorCode: String, isWarmingUp: Bool) {
    self.printerId = printerId
    self.isOnline = isOnline
    self.isPrinting = isPrinting
    self.jobsInQueue = jobsInQueue
    self.statusMessage = statusMessage
    self.inkLevel = inkLevel
    self.tonerLevel = tonerLevel
    self.paperLevel = paperLevel
    self.errorCode = errorCode
    self.isWarmingUp = isWarmingUp
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrinterStatus {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrinterStatus {
    return PrinterStatus(
      printerId: r.readString(),
      isOnline: r.readBool(),
      isPrinting: r.readBool(),
      jobsInQueue: r.readInt(),
      statusMessage: r.readString(),
      inkLevel: r.readInt(),
      tonerLevel: r.readInt(),
      paperLevel: r.readInt(),
      errorCode: r.readString(),
      isWarmingUp: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(printerId)
    writer.writeBool(isOnline)
    writer.writeBool(isPrinting)
    writer.writeInt(jobsInQueue)
    writer.writeString(statusMessage)
    writer.writeInt(inkLevel)
    writer.writeInt(tonerLevel)
    writer.writeInt(paperLevel)
    writer.writeString(errorCode)
    writer.writeBool(isWarmingUp)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct DiscoveredPrinter: NitroEncodable {
  public var id: String
  public var name: String
  public var host: String
  public var port: Int64
  public var serviceType: String
  public var uri: String
  public var isAvailable: Bool

  public init(id: String, name: String, host: String, port: Int64, serviceType: String, uri: String, isAvailable: Bool) {
    self.id = id
    self.name = name
    self.host = host
    self.port = port
    self.serviceType = serviceType
    self.uri = uri
    self.isAvailable = isAvailable
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> DiscoveredPrinter {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> DiscoveredPrinter {
    return DiscoveredPrinter(
      id: r.readString(),
      name: r.readString(),
      host: r.readString(),
      port: r.readInt(),
      serviceType: r.readString(),
      uri: r.readString(),
      isAvailable: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(id)
    writer.writeString(name)
    writer.writeString(host)
    writer.writeInt(port)
    writer.writeString(serviceType)
    writer.writeString(uri)
    writer.writeBool(isAvailable)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct PrinterStatusDetail: NitroEncodable {
  public var printerId: String
  public var isOnline: Bool
  public var isReady: Bool
  public var hasPaperJam: Bool
  public var isOutOfPaper: Bool
  public var isOutOfInk: Bool
  public var inkLevelBlack: Int64
  public var inkLevelCyan: Int64
  public var inkLevelMagenta: Int64
  public var inkLevelYellow: Int64
  public var tonerLevel: Int64
  public var paperLevel: Int64
  public var jobsInQueue: Int64
  public var isWarmingUp: Bool
  public var printerState: String
  public var stateReasons: String
  public var statusMessage: String
  public var errorCode: String
  public var isDuplexSupported: Bool
  public var isColorSupported: Bool

  public init(printerId: String, isOnline: Bool, isReady: Bool, hasPaperJam: Bool, isOutOfPaper: Bool, isOutOfInk: Bool, inkLevelBlack: Int64, inkLevelCyan: Int64, inkLevelMagenta: Int64, inkLevelYellow: Int64, tonerLevel: Int64, paperLevel: Int64, jobsInQueue: Int64, isWarmingUp: Bool, printerState: String, stateReasons: String, statusMessage: String, errorCode: String, isDuplexSupported: Bool, isColorSupported: Bool) {
    self.printerId = printerId
    self.isOnline = isOnline
    self.isReady = isReady
    self.hasPaperJam = hasPaperJam
    self.isOutOfPaper = isOutOfPaper
    self.isOutOfInk = isOutOfInk
    self.inkLevelBlack = inkLevelBlack
    self.inkLevelCyan = inkLevelCyan
    self.inkLevelMagenta = inkLevelMagenta
    self.inkLevelYellow = inkLevelYellow
    self.tonerLevel = tonerLevel
    self.paperLevel = paperLevel
    self.jobsInQueue = jobsInQueue
    self.isWarmingUp = isWarmingUp
    self.printerState = printerState
    self.stateReasons = stateReasons
    self.statusMessage = statusMessage
    self.errorCode = errorCode
    self.isDuplexSupported = isDuplexSupported
    self.isColorSupported = isColorSupported
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> PrinterStatusDetail {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> PrinterStatusDetail {
    return PrinterStatusDetail(
      printerId: r.readString(),
      isOnline: r.readBool(),
      isReady: r.readBool(),
      hasPaperJam: r.readBool(),
      isOutOfPaper: r.readBool(),
      isOutOfInk: r.readBool(),
      inkLevelBlack: r.readInt(),
      inkLevelCyan: r.readInt(),
      inkLevelMagenta: r.readInt(),
      inkLevelYellow: r.readInt(),
      tonerLevel: r.readInt(),
      paperLevel: r.readInt(),
      jobsInQueue: r.readInt(),
      isWarmingUp: r.readBool(),
      printerState: r.readString(),
      stateReasons: r.readString(),
      statusMessage: r.readString(),
      errorCode: r.readString(),
      isDuplexSupported: r.readBool(),
      isColorSupported: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(printerId)
    writer.writeBool(isOnline)
    writer.writeBool(isReady)
    writer.writeBool(hasPaperJam)
    writer.writeBool(isOutOfPaper)
    writer.writeBool(isOutOfInk)
    writer.writeInt(inkLevelBlack)
    writer.writeInt(inkLevelCyan)
    writer.writeInt(inkLevelMagenta)
    writer.writeInt(inkLevelYellow)
    writer.writeInt(tonerLevel)
    writer.writeInt(paperLevel)
    writer.writeInt(jobsInQueue)
    writer.writeBool(isWarmingUp)
    writer.writeString(printerState)
    writer.writeString(stateReasons)
    writer.writeString(statusMessage)
    writer.writeString(errorCode)
    writer.writeBool(isDuplexSupported)
    writer.writeBool(isColorSupported)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableInt: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableInt {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableInt {
    return NitroNullableInt(
      hasValue: r.readBool(),
      value: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Int64? { hasValue ? value : nil }
  public static func fromNullable(_ v: Int64?) -> NitroNullableInt {
    return NitroNullableInt(hasValue: v != nil, value: v ?? 0)
  }
}

public struct NitroNullableDouble: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableDouble {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableDouble {
    return NitroNullableDouble(
      hasValue: r.readBool(),
      value: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Double? { hasValue ? value : nil }
  public static func fromNullable(_ v: Double?) -> NitroNullableDouble {
    return NitroNullableDouble(hasValue: v != nil, value: v ?? 0.0)
  }
}

public struct NitroNullableBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableBool {
    return NitroNullableBool(
      hasValue: r.readBool(),
      value: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Bool? { hasValue ? value : nil }
  public static func fromNullable(_ v: Bool?) -> NitroNullableBool {
    return NitroNullableBool(hasValue: v != nil, value: v ?? false)
  }
}

public class NitroRecordWriter {
  public var bytes: [UInt8] = []
  public init() {}
  public func writeInt(_ v: Int64) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeInt32(_ v: Int32) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeDouble(_ v: Double) {
      var val = v.bitPattern.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeBool(_ v: Bool) {
      bytes.append(v ? 1 : 0)
  }
  public func writeString(_ v: String) {
      let utf8 = Array(v.utf8)
      writeInt32(Int32(utf8.count))
      bytes.append(contentsOf: utf8)
  }
  public func writeNullTag(_ isNull: Bool) {
      bytes.append(isNull ? 0 : 1)
  }
  public func writeBlob(_ v: Data) {
      writeInt32(Int32(v.count))
      bytes.append(contentsOf: Array(v))
  }
  public func toNative() -> UnsafeMutablePointer<UInt8>? {
      let total = 4 + bytes.count
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
      var length = Int32(bytes.count).littleEndian
      _ = memcpy(ptr, &length, 4)
      if bytes.count > 0 {
          _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
      }
      return ptr
  }
  public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items { writeItem(w, item) }
      return w.toNative()
  }
  /// Encodes a list with a per-item byte-offset table for O(1) random access.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
  public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      var blobs: [[UInt8]] = []
      for item in items {
          let w = NitroRecordWriter()
          writeItem(w, item)
          blobs.append(w.bytes)
      }
      var pos = 4 + 8 * blobs.count
      var offsets: [Int64] = []
      for blob in blobs {
          offsets.append(Int64(pos))
          pos += blob.count
      }
      let w = NitroRecordWriter()
      w.writeInt32(Int32(blobs.count))
      for off in offsets { w.writeInt(off) }
      for blob in blobs { w.bytes.append(contentsOf: blob) }
      return w.toNative()
  }
}

public class NitroRecordReader {
  public let bytes: UnsafeMutablePointer<UInt8>
  public var pos: Int = 0
  public init(ptr: UnsafeMutablePointer<UInt8>) {
      self.bytes = ptr.advanced(by: 4)
  }
  public init(payload: UnsafeMutablePointer<UInt8>) {
      self.bytes = payload
  }
  public func readInt() -> Int64 {
      var v: Int64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Int64(littleEndian: v)
  }
  public func readInt32() -> Int32 {
      var v: Int32 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 4)
      pos += 4
      return Int32(littleEndian: v)
  }
  public func readDouble() -> Double {
      var v: UInt64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Double(bitPattern: UInt64(littleEndian: v))
  }
  public func readBool() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v != 0
  }
  public func readString() -> String {
      let len = Int(readInt32())
      guard len > 0 else { return "" }
      let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
      pos += len
      return s
  }
  public func readNullTag() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v == 0
  }
  public func readBlob() -> Data {
      let len = Int(readInt32())
      let data = Data(bytes: bytes.advanced(by: pos), count: len)
      pos += len
      return data
  }
  public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
      let len = Int(readInt32())
      if (len == 0) { return nil }
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
      ptr.initialize(from: bytes.advanced(by: pos), count: len)
      pos += len
      return ptr
  }
  public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
  /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// The offset table is skipped; items are read sequentially after it.
  public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      r.pos += Int(count) * 8  // skip Int64 offset table
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
}

/**
 * Protocol for the NitroPrinting module.
 * Conform to this in your Swift source code.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroPrintingProtocol: AnyObject {
    // source: nitro_printing.native.dart:17
    func isPrintingSupported() -> Bool
    // source: nitro_printing.native.dart:18
    func getPrintersCount() -> Int64
    // source: nitro_printing.native.dart:19
    func getPrinterDriverVersion(printerId: String) -> String
    // source: nitro_printing.native.dart:25
    func getAllPrinters() async throws -> [PrinterInfo]
    // source: nitro_printing.native.dart:28
    func getPrinterAt(index: Int64) async throws -> PrinterInfo
    // source: nitro_printing.native.dart:31
    func getDefaultPrinter() async throws -> PrinterInfo
    // source: nitro_printing.native.dart:34
    func getPrinterCapabilities(printerId: String) async throws -> PrinterCapabilities
    // source: nitro_printing.native.dart:39
    func printText(text: String, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:42
    func printImage(imageData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:48
    func printPdf(pdfData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:51
    func printDocument(document: PrintDocument, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:57
    func printFile(filePath: String, settings: PrintSettings?) async throws -> Bool
    // source: nitro_printing.native.dart:63
    func renderPreview(document: PrintDocument, settings: PrintSettings?) async throws -> PreviewResult
    // source: nitro_printing.native.dart:70
    func getPageCount(document: PrintDocument) async throws -> Int64
    // source: nitro_printing.native.dart:74
    func printToFile(document: PrintDocument, outputPath: String, settings: PrintSettings?) async throws -> Bool
    // source: nitro_printing.native.dart:83
    func cancelPrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:86
    func pausePrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:89
    func resumePrintJob(jobId: String) async throws -> Bool
    // source: nitro_printing.native.dart:92
    func clearPrintQueue() async throws -> Bool
    // source: nitro_printing.native.dart:95
    func getPrintJobsCount() async throws -> Int64
    // source: nitro_printing.native.dart:98
    func getPrintJobAt(index: Int64) async throws -> PrintJob
    // source: nitro_printing.native.dart:102
    func getPrintJobStatus(jobId: String) async throws -> PrintJob
    // source: nitro_printing.native.dart:109
    func startPrinterDiscovery() async throws -> Bool
    // source: nitro_printing.native.dart:112
    func stopPrinterDiscovery() async throws -> Bool
    // source: nitro_printing.native.dart:118
    func testPrinterConnection(printerId: String, timeoutSeconds: Int64?) async throws -> Bool
    // source: nitro_printing.native.dart:122
    func setDefaultPrinter(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:132
    func openSystemPrintQueue(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:136
    func openPrinterProperties(printerId: String) async throws -> Bool
    // source: nitro_printing.native.dart:144
    func printRaw(data: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:149
    func printEscPos(escPosData: Data, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:157
    func printZpl(zpl: String, settings: PrintSettings?) async throws -> PrintResult
    // source: nitro_printing.native.dart:163
    func cancelRawPrint() async throws -> Bool
    // source: nitro_printing.native.dart:170
    func getPrinterStatusDetail(printerId: String, timeoutSeconds: Int64?) async throws -> PrinterStatusDetail
    var onPrintJobChanged: AnyPublisher<PrintJobUpdate, Never> { get }
    var onPrinterStatusChanged: AnyPublisher<PrinterStatus, Never> { get }
    var onPrinterDiscovered: AnyPublisher<DiscoveredPrinter, Never> { get }
}

public class NitroPrintingRegistry {
    public static var impl: HybridNitroPrintingProtocol?

    public static func register(_ impl: HybridNitroPrintingProtocol) {
        NitroPrintingRegistry.impl = impl
    }

    // Stream: onPrintJobChanged cancellables keyed by dartPort
    public static var _onPrintJobChangedCancellables = [Int64: AnyCancellable]()

    // Stream: onPrinterStatusChanged cancellables keyed by dartPort
    public static var _onPrinterStatusChangedCancellables = [Int64: AnyCancellable]()

    // Stream: onPrinterDiscovered cancellables keyed by dartPort
    public static var _onPrinterDiscoveredCancellables = [Int64: AnyCancellable]()
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_printing.native.dart:17
@_cdecl("_nitro_printing_call_isPrintingSupported")
public func _nitro_printing_call_isPrintingSupported() -> Int8 {
    return Int8((NitroPrintingRegistry.impl?.isPrintingSupported() ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:18
@_cdecl("_nitro_printing_call_getPrintersCount")
public func _nitro_printing_call_getPrintersCount() -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    return impl.getPrintersCount()
}

// source: nitro_printing.native.dart:19
@_cdecl("_nitro_printing_call_getPrinterDriverVersion")
public func _nitro_printing_call_getPrinterDriverVersion(_ printerId: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    return strdup(NitroPrintingRegistry.impl?.getPrinterDriverVersion(printerId: printerIdStr) ?? "")
}

// source: nitro_printing.native.dart:25
@_cdecl("_nitro_printing_call_getAllPrinters")
public func _nitro_printing_call_getAllPrinters() -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [PrinterInfo]? = nil
    Task.detached {
        result = try? await impl.getAllPrinters()
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeIndexedList(r) { w, e in e.writeFields(w) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:28
@_cdecl("_nitro_printing_call_getPrinterAt")
public func _nitro_printing_call_getPrinterAt(_ index: Int64) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrinterInfo? = nil
    Task.detached {
        result = try? await impl.getPrinterAt(index: index)
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:31
@_cdecl("_nitro_printing_call_getDefaultPrinter")
public func _nitro_printing_call_getDefaultPrinter() -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrinterInfo? = nil
    Task.detached {
        result = try? await impl.getDefaultPrinter()
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:34
@_cdecl("_nitro_printing_call_getPrinterCapabilities")
public func _nitro_printing_call_getPrinterCapabilities(_ printerId: UnsafePointer<CChar>?) -> UnsafeMutableRawPointer? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrinterCapabilities? = nil
    Task.detached {
        result = try? await impl.getPrinterCapabilities(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:39
@_cdecl("_nitro_printing_call_printText")
public func _nitro_printing_call_printText(_ text: UnsafePointer<CChar>?, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let textStr = text != nil ? String(cString: text!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printText(text: textStr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:42
@_cdecl("_nitro_printing_call_printImage")
public func _nitro_printing_call_printImage(_ imageData: UnsafeMutablePointer<UInt8>?, _ imageData_length: Int64, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let imageDataArr = imageData.map { Data(bytes: $0, count: Int(imageData_length)) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printImage(imageData: imageDataArr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:48
@_cdecl("_nitro_printing_call_printPdf")
public func _nitro_printing_call_printPdf(_ pdfData: UnsafeMutablePointer<UInt8>?, _ pdfData_length: Int64, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let pdfDataArr = pdfData.map { Data(bytes: $0, count: Int(pdfData_length)) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printPdf(pdfData: pdfDataArr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:51
@_cdecl("_nitro_printing_call_printDocument")
public func _nitro_printing_call_printDocument(_ document: UnsafeMutableRawPointer?, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printDocument(document: PrintDocument.fromNative(document!.assumingMemoryBound(to: UInt8.self)), settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:57
@_cdecl("_nitro_printing_call_printFile")
public func _nitro_printing_call_printFile(_ filePath: UnsafePointer<CChar>?, _ settings: UnsafeMutableRawPointer?) -> Int8 {
    let filePathStr = filePath != nil ? String(cString: filePath!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.printFile(filePath: filePathStr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:63
@_cdecl("_nitro_printing_call_renderPreview")
public func _nitro_printing_call_renderPreview(_ document: UnsafeMutableRawPointer?, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PreviewResult? = nil
    Task.detached {
        result = try? await impl.renderPreview(document: PrintDocument.fromNative(document!.assumingMemoryBound(to: UInt8.self)), settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_PreviewResultC>.allocate(capacity: 1)
    ptr.initialize(to: _PreviewResultC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_printing.native.dart:70
@_cdecl("_nitro_printing_call_getPageCount")
public func _nitro_printing_call_getPageCount(_ document: UnsafeMutableRawPointer?) -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.getPageCount(document: PrintDocument.fromNative(document!.assumingMemoryBound(to: UInt8.self)))
        sema.signal()
    }
    sema.wait()
    return result ?? 0
}

// source: nitro_printing.native.dart:74
@_cdecl("_nitro_printing_call_printToFile")
public func _nitro_printing_call_printToFile(_ document: UnsafeMutableRawPointer?, _ outputPath: UnsafePointer<CChar>?, _ settings: UnsafeMutableRawPointer?) -> Int8 {
    let outputPathStr = outputPath != nil ? String(cString: outputPath!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.printToFile(document: PrintDocument.fromNative(document!.assumingMemoryBound(to: UInt8.self)), outputPath: outputPathStr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:83
@_cdecl("_nitro_printing_call_cancelPrintJob")
public func _nitro_printing_call_cancelPrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.cancelPrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:86
@_cdecl("_nitro_printing_call_pausePrintJob")
public func _nitro_printing_call_pausePrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.pausePrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:89
@_cdecl("_nitro_printing_call_resumePrintJob")
public func _nitro_printing_call_resumePrintJob(_ jobId: UnsafePointer<CChar>?) -> Int8 {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.resumePrintJob(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:92
@_cdecl("_nitro_printing_call_clearPrintQueue")
public func _nitro_printing_call_clearPrintQueue() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.clearPrintQueue()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:95
@_cdecl("_nitro_printing_call_getPrintJobsCount")
public func _nitro_printing_call_getPrintJobsCount() -> Int64 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.getPrintJobsCount()
        sema.signal()
    }
    sema.wait()
    return result ?? 0
}

// source: nitro_printing.native.dart:98
@_cdecl("_nitro_printing_call_getPrintJobAt")
public func _nitro_printing_call_getPrintJobAt(_ index: Int64) -> UnsafeMutableRawPointer? {
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintJob? = nil
    Task.detached {
        result = try? await impl.getPrintJobAt(index: index)
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:102
@_cdecl("_nitro_printing_call_getPrintJobStatus")
public func _nitro_printing_call_getPrintJobStatus(_ jobId: UnsafePointer<CChar>?) -> UnsafeMutableRawPointer? {
    let jobIdStr = jobId != nil ? String(cString: jobId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintJob? = nil
    Task.detached {
        result = try? await impl.getPrintJobStatus(jobId: jobIdStr)
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:109
@_cdecl("_nitro_printing_call_startPrinterDiscovery")
public func _nitro_printing_call_startPrinterDiscovery() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.startPrinterDiscovery()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:112
@_cdecl("_nitro_printing_call_stopPrinterDiscovery")
public func _nitro_printing_call_stopPrinterDiscovery() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.stopPrinterDiscovery()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:118
@_cdecl("_nitro_printing_call_testPrinterConnection")
public func _nitro_printing_call_testPrinterConnection(_ printerId: UnsafePointer<CChar>?, _ timeoutSeconds: UnsafeMutableRawPointer?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.testPrinterConnection(printerId: printerIdStr, timeoutSeconds: NitroNullableInt.fromNative(timeoutSeconds!.assumingMemoryBound(to: UInt8.self)).nullable)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:122
@_cdecl("_nitro_printing_call_setDefaultPrinter")
public func _nitro_printing_call_setDefaultPrinter(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.setDefaultPrinter(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:132
@_cdecl("_nitro_printing_call_openSystemPrintQueue")
public func _nitro_printing_call_openSystemPrintQueue(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.openSystemPrintQueue(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:136
@_cdecl("_nitro_printing_call_openPrinterProperties")
public func _nitro_printing_call_openPrinterProperties(_ printerId: UnsafePointer<CChar>?) -> Int8 {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.openPrinterProperties(printerId: printerIdStr)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:144
@_cdecl("_nitro_printing_call_printRaw")
public func _nitro_printing_call_printRaw(_ data: UnsafeMutablePointer<UInt8>?, _ data_length: Int64, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let dataArr = data.map { Data(bytes: $0, count: Int(data_length)) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printRaw(data: dataArr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:149
@_cdecl("_nitro_printing_call_printEscPos")
public func _nitro_printing_call_printEscPos(_ escPosData: UnsafeMutablePointer<UInt8>?, _ escPosData_length: Int64, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let escPosDataArr = escPosData.map { Data(bytes: $0, count: Int(escPosData_length)) } ?? Data()
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printEscPos(escPosData: escPosDataArr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:157
@_cdecl("_nitro_printing_call_printZpl")
public func _nitro_printing_call_printZpl(_ zpl: UnsafePointer<CChar>?, _ settings: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let zplStr = zpl != nil ? String(cString: zpl!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrintResult? = nil
    Task.detached {
        result = try? await impl.printZpl(zpl: zplStr, settings: settings.map { PrintSettings.fromNative($0.assumingMemoryBound(to: UInt8.self)) })
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_printing.native.dart:163
@_cdecl("_nitro_printing_call_cancelRawPrint")
public func _nitro_printing_call_cancelRawPrint() -> Int8 {
    guard let impl = NitroPrintingRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.cancelRawPrint()
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_printing.native.dart:170
@_cdecl("_nitro_printing_call_getPrinterStatusDetail")
public func _nitro_printing_call_getPrinterStatusDetail(_ printerId: UnsafePointer<CChar>?, _ timeoutSeconds: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let printerIdStr = printerId != nil ? String(cString: printerId!) : ""
    guard let impl = NitroPrintingRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: PrinterStatusDetail? = nil
    Task.detached {
        result = try? await impl.getPrinterStatusDetail(printerId: printerIdStr, timeoutSeconds: NitroNullableInt.fromNative(timeoutSeconds!.assumingMemoryBound(to: UInt8.self)).nullable)
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

@_cdecl("_nitro_printing_register_onPrintJobChanged_stream")
public func _nitro_printing_register_onPrintJobChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroPrintingRegistry._onPrintJobChangedCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrintJobChanged.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroPrintingRegistry._onPrintJobChangedCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_printing_release_onPrintJobChanged_stream")
public func _nitro_printing_release_onPrintJobChanged_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrintJobChangedCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrintJobChangedCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_printing_register_onPrinterStatusChanged_stream")
public func _nitro_printing_register_onPrinterStatusChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroPrintingRegistry._onPrinterStatusChangedCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrinterStatusChanged.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroPrintingRegistry._onPrinterStatusChangedCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_printing_release_onPrinterStatusChanged_stream")
public func _nitro_printing_release_onPrinterStatusChanged_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrinterStatusChangedCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrinterStatusChangedCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_printing_register_onPrinterDiscovered_stream")
public func _nitro_printing_register_onPrinterDiscovered_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroPrintingRegistry._onPrinterDiscoveredCancellables[dartPort] =
        NitroPrintingRegistry.impl?.onPrinterDiscovered.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroPrintingRegistry._onPrinterDiscoveredCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_printing_release_onPrinterDiscovered_stream")
public func _nitro_printing_release_onPrinterDiscovered_stream(_ dartPort: Int64) {
    NitroPrintingRegistry._onPrinterDiscoveredCancellables[dartPort]?.cancel()
    NitroPrintingRegistry._onPrinterDiscoveredCancellables.removeValue(forKey: dartPort)
}
