// Generated by Nitrogen Modules. Do not edit.
// Generated from: nitro_printing.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

// --- Enums ---
typedef enum {
  PRINTSTATE_IDLE = 0,
  PRINTSTATE_PRINTING = 1,
  PRINTSTATE_COMPLETED = 2,
  PRINTSTATE_CANCELLED = 3,
  PRINTSTATE_FAILED = 4,
  PRINTSTATE_PAUSED = 5,
} PrintState;

typedef enum {
  PRINTQUALITY_DRAFT = 0,
  PRINTQUALITY_NORMAL = 1,
  PRINTQUALITY_HIGH = 2,
  PRINTQUALITY_BEST = 3,
} PrintQuality;

typedef enum {
  PAPERSIZE_A4 = 0,
  PAPERSIZE_A5 = 1,
  PAPERSIZE_LETTER = 2,
  PAPERSIZE_LEGAL = 3,
  PAPERSIZE_CUSTOM = 4,
} PaperSize;

typedef enum {
  PAPERORIENTATION_PORTRAIT = 0,
  PAPERORIENTATION_LANDSCAPE = 1,
} PaperOrientation;

typedef enum {
  DOCUMENTTYPE_PLAIN_TEXT = 0,
  DOCUMENTTYPE_HTML = 1,
  DOCUMENTTYPE_PDF = 2,
  DOCUMENTTYPE_IMAGE = 3,
} DocumentType;

// --- Structs ---
#ifndef NITRO_STRUCT_PRINTERINFO_DEFINED
#define NITRO_STRUCT_PRINTERINFO_DEFINED
typedef struct {
  const char* id; 
  const char* name; 
  const char* address; 
  int8_t isDefault; 
  int8_t isAvailable; 
} PrinterInfo;
#endif // NITRO_STRUCT_PRINTERINFO_DEFINED

#ifndef NITRO_STRUCT_PRINTERCAPABILITIES_DEFINED
#define NITRO_STRUCT_PRINTERCAPABILITIES_DEFINED
typedef struct {
  int8_t supportsColor; 
  int8_t supportsDuplex; 
  int8_t supportsCopy; 
  int64_t maxCopies; 
  double minMarginTop; 
  double minMarginBottom; 
  double minMarginLeft; 
  double minMarginRight; 
  int8_t supportsA4; 
  int8_t supportsA5; 
  int8_t supportsLetter; 
  int8_t supportsLegal; 
  int8_t supportsDraftQuality; 
  int8_t supportsNormalQuality; 
  int8_t supportsHighQuality; 
  int8_t supportsBestQuality; 
} PrinterCapabilities;
#endif // NITRO_STRUCT_PRINTERCAPABILITIES_DEFINED

#ifndef NITRO_STRUCT_PRINTSETTINGS_DEFINED
#define NITRO_STRUCT_PRINTSETTINGS_DEFINED
typedef struct {
  const char* printerId; 
  int32_t paperSize; 
  int32_t orientation; 
  int32_t quality; 
  int64_t copies; 
  int8_t collate; 
  int8_t duplex; 
  int8_t color; 
  double marginTop; 
  double marginBottom; 
  double marginLeft; 
  double marginRight; 
  const char* jobName; 
} PrintSettings;
#endif // NITRO_STRUCT_PRINTSETTINGS_DEFINED

#ifndef NITRO_STRUCT_PRINTDOCUMENT_DEFINED
#define NITRO_STRUCT_PRINTDOCUMENT_DEFINED
typedef struct {
  const char* id; 
  const char* title; 
  int32_t type; 
  uint8_t* data; 
  int64_t dataLength; /* synthesized: element count for data buffer */
} PrintDocument;
#endif // NITRO_STRUCT_PRINTDOCUMENT_DEFINED

#ifndef NITRO_STRUCT_PRINTJOB_DEFINED
#define NITRO_STRUCT_PRINTJOB_DEFINED
typedef struct {
  const char* id; 
  const char* printerId; 
  const char* documentTitle; 
  int32_t state; 
  int64_t progress; 
  int64_t createdAtMillis; 
  int64_t completedAtMillis; 
  const char* errorMessage; 
  int64_t pagesPrinted; 
} PrintJob;
#endif // NITRO_STRUCT_PRINTJOB_DEFINED

#ifndef NITRO_STRUCT_PRINTRESULT_DEFINED
#define NITRO_STRUCT_PRINTRESULT_DEFINED
typedef struct {
  int8_t success; 
  const char* jobId; 
  const char* errorMessage; 
  const char* errorCode; 
} PrintResult;
#endif // NITRO_STRUCT_PRINTRESULT_DEFINED

#ifndef NITRO_STRUCT_PRINTJOBUPDATE_DEFINED
#define NITRO_STRUCT_PRINTJOBUPDATE_DEFINED
typedef struct {
  const char* jobId; 
  int32_t state; 
  int64_t progress; 
  const char* message; 
} PrintJobUpdate;
#endif // NITRO_STRUCT_PRINTJOBUPDATE_DEFINED

#ifndef NITRO_STRUCT_PRINTERSTATUS_DEFINED
#define NITRO_STRUCT_PRINTERSTATUS_DEFINED
typedef struct {
  const char* printerId; 
  int8_t isOnline; 
  int8_t isPrinting; 
  int64_t jobsInQueue; 
  const char* statusMessage; 
  int64_t inkLevel; 
  int64_t tonerLevel; 
} PrinterStatus;
#endif // NITRO_STRUCT_PRINTERSTATUS_DEFINED

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT intptr_t nitro_printing_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_printing_get_error(void);
NITRO_EXPORT void nitro_printing_clear_error(void);



// Methods
NITRO_EXPORT int64_t nitro_printing_get_printers_count(void);
NITRO_EXPORT void* nitro_printing_get_printer_at(int64_t index);
NITRO_EXPORT void* nitro_printing_get_default_printer(void);
NITRO_EXPORT void* nitro_printing_print_text(const char* text, void* settings);
NITRO_EXPORT void* nitro_printing_print_image(uint8_t* imageData, int64_t imageData_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_pdf(uint8_t* pdfData, int64_t pdfData_length, void* settings);
NITRO_EXPORT void* nitro_printing_print_document(void* document, void* settings);
NITRO_EXPORT int8_t nitro_printing_cancel_print_job(const char* jobId);
NITRO_EXPORT int64_t nitro_printing_get_print_jobs_count(void);
NITRO_EXPORT void* nitro_printing_get_print_job_at(int64_t index);
NITRO_EXPORT int8_t nitro_printing_is_printing_supported(void);
NITRO_EXPORT const char* nitro_printing_get_printer_driver_version(const char* printerId);
NITRO_EXPORT void* nitro_printing_get_printer_capabilities(const char* printerId);
NITRO_EXPORT int8_t nitro_printing_print_file(const char* filePath, void* settings);

// Streams
// Stream<PrintJobUpdate> onPrintJobChanged
NITRO_EXPORT void nitro_printing_register_on_print_job_changed_stream(int64_t dart_port);
NITRO_EXPORT void nitro_printing_release_on_print_job_changed_stream(int64_t dart_port);
// Stream<PrinterStatus> onPrinterStatusChanged
NITRO_EXPORT void nitro_printing_register_on_printer_status_changed_stream(int64_t dart_port);
NITRO_EXPORT void nitro_printing_release_on_printer_status_changed_stream(int64_t dart_port);

// Struct release functions
NITRO_EXPORT void nitro_printing_release_PrinterInfo(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrinterCapabilities(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrintSettings(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrintDocument(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrintJob(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrintResult(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrintJobUpdate(void* ptr);
NITRO_EXPORT void nitro_printing_release_PrinterStatus(void* ptr);

#ifdef __cplusplus
}
#endif
