// HybridNitroPrinting — NativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../lib/src/generated/cpp/nitro_printing.native.g.h"

#include <cstdlib>
#include <cstring>
#include <string>

class HybridNitroPrintingImpl final : public HybridNitroPrinting {
public:
    bool isPrintingSupported() override { return false; }
    int64_t getPrintersCount() override { return 0; }
    NitroCppBuffer getAllPrinters() override {
        // Wire format: [4-byte payload_len LE][4-byte count LE] — empty list (count=0).
        uint8_t* buf = static_cast<uint8_t*>(malloc(8));
        memset(buf, 0, 8); // payload_len=4, count=0
        buf[0] = 4; // payload_len = 4 bytes (just the count field)
        return NitroCppBuffer{buf, 8};
    }
    PrinterInfo getPrinterAt(int64_t) override { return PrinterInfo{"", "", "", 0, 0}; }
    PrinterInfo getDefaultPrinter() override { return PrinterInfo{"", "", "", 0, 0}; }
    std::string getPrinterDriverVersion(const std::string&) override { return ""; }
    PrinterCapabilities getPrinterCapabilities(const std::string&) override { return PrinterCapabilities{}; }
    PrintResult printText(const std::string&, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    PrintResult printImage(const uint8_t*, size_t, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    PrintResult printPdf(const uint8_t*, size_t, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    PrintResult printDocument(const PrintDocument&, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    bool printFile(const std::string&, const PrintSettings&) override { return false; }
    PreviewResult renderPreview(const PrintDocument&, const PrintSettings&) override { return PreviewResult{nullptr, 0}; }
    int64_t getPageCount(const PrintDocument&) override { return 0; }
    bool printToFile(const PrintDocument&, const std::string&, const PrintSettings&) override { return false; }
    bool cancelPrintJob(const std::string&) override { return false; }
    bool pausePrintJob(const std::string&) override { return false; }
    bool resumePrintJob(const std::string&) override { return false; }
    bool clearPrintQueue() override { return false; }
    int64_t getPrintJobsCount() override { return 0; }
    PrintJob getPrintJobAt(int64_t) override { return PrintJob{"", "", "", PRINTSTATE_IDLE, 0, 0, 0, "", 0}; }
    PrintJob getPrintJobStatus(const std::string&) override { return PrintJob{"", "", "", PRINTSTATE_IDLE, 0, 0, 0, "", 0}; }
    bool startPrinterDiscovery() override { return false; }
    bool stopPrinterDiscovery() override { return false; }
    bool testPrinterConnection(const std::string&, int64_t) override { return false; }
    bool setDefaultPrinter(const std::string&) override { return false; }
    bool openSystemPrintQueue(const std::string&) override { return false; }
    bool openPrinterProperties(const std::string&) override { return false; }
    PrintResult printRaw(const uint8_t*, size_t, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    PrintResult printEscPos(const uint8_t*, size_t, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    PrintResult printZpl(const std::string&, const PrintSettings&) override { return PrintResult{0, "", "Not implemented", ""}; }
    bool cancelRawPrint() override { return false; }
    PrinterStatusDetail getPrinterStatusDetail(const std::string&, int64_t) override { return PrinterStatusDetail{}; }
};

static HybridNitroPrintingImpl g_impl;

// Auto-register on shared library load — no manual init call needed.
#if (defined(__linux__) && !defined(__ANDROID__))
#if defined(_WIN32)
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_printing_register_impl(&g_impl); }
  };
  _AutoRegister _auto_register_instance;
}
#else
__attribute__((constructor))
static void nitro_printing_auto_register() {
    nitro_printing_register_impl(&g_impl);
}
#endif
#endif // auto-register on C++ platforms
